#ifndef DB2STRUCTURE_REFERENCE_H
#define DB2STRUCTURE_REFERENCE_H

// AUTO-GENERATED by CoreAlign/tools/gen_reference.py -- DO NOT EDIT.
// Inert reference map of the MoP 5.4.8.18414 client WDB2 tables the core does NOT model.
// This header is NEVER #included. Activating a table = move its struct into DB2Structure.h,
// add its fmt to DB2fmt.h, and register a storage loader.
//
// Localized strings are the client's single WDB2 string column, emitted as `char*`.
// The live core models DBC/DB2 strings as `DBCString`; the two are layout-equivalent for
// this documentation map.
//
// Self-contained fixed-width integer typedefs (guarded; an identical-type redefinition is
// legal should this header ever be included after Platform/Define.h).
#ifndef DBC_REF_INT_TYPES
#define DBC_REF_INT_TYPES
#include <cstdint>
typedef uint8_t  uint8;
typedef uint16_t uint16;
typedef uint32_t uint32;
typedef uint64_t uint64;
typedef int8_t   int8;
typedef int16_t  int16;
typedef int32_t  int32;
typedef int64_t  int64;
#endif

/*
 * DB2 MAP -- 58 client MoP tables (build 5.4.8.18414)
 *   ACTIVE  = modelled + loaded by the core.
 *   DORMANT = modelled struct present but its loader is disabled.
 *   DOC     = inert reference struct in this header (core does not model it).
 *
 *   BattlePetAbility                 DOC   (8 cols)
 *   BattlePetAbilityEffect           DOC   (7 cols)
 *   BattlePetAbilityState            DOC   (4 cols)
 *   BattlePetAbilityTurn             DOC   (6 cols)
 *   BattlePetBreedQuality            DOC   (3 cols)
 *   BattlePetBreedState              DOC   (4 cols)
 *   BattlePetEffectProperties        DOC   (4 cols)
 *   BattlePetNPCTeamMember           DOC   (2 cols)
 *   BattlePetSpecies                 DOC   (9 cols)
 *   BattlePetSpeciesState            DOC   (4 cols)
 *   BattlePetSpeciesXAbility         DOC   (5 cols)
 *   BattlePetState                   DOC   (4 cols)
 *   BattlePetVisual                  DOC   (8 cols)
 *   BroadcastText                    DOC   (9 cols)
 *   Creature                         DOC   (10 cols)
 *   CreatureDifficulty               DOC   (7 cols)
 *   Curve                            DOC   (3 cols)
 *   CurvePoint                       DOC   (4 cols)
 *   DeviceBlacklist                  DOC   (3 cols)
 *   DriverBlacklist                  DOC   (8 cols)
 *   GameObjects                      DOC   (9 cols)
 *   Item                             ACTIVE
 *   Item-sparse                      DOC   (68 cols)
 *   ItemCurrencyCost                 ACTIVE
 *   ItemExtendedCost                 ACTIVE
 *   ItemToBattlePet                  DOC   (2 cols)
 *   ItemToMountSpell                 DOC   (2 cols)
 *   ItemUpgrade                      DOC   (6 cols)
 *   KeyChain                         DOC   (2 cols)
 *   Locale                           DOC   (6 cols)
 *   Location                         DOC   (3 cols)
 *   MapChallengeMode                 DOC   (6 cols)
 *   MarketingPromotionsXLocale       DOC   (8 cols)
 *   Path                             DOC   (8 cols)
 *   PathNode                         DOC   (4 cols)
 *   PathNodeProperty                 DOC   (5 cols)
 *   PathProperty                     DOC   (4 cols)
 *   QuestPackageItem                 DOC   (5 cols)
 *   RulesetItemUpgrade               DOC   (4 cols)
 *   RulesetRaidLootUpgrade           DOC   (5 cols)
 *   SceneScript                      ACTIVE
 *   SceneScriptPackage               DOC   (2 cols)
 *   SceneScriptPackageMember         DOC   (5 cols)
 *   SpellEffectCameraShakes          DOC   (2 cols)
 *   SpellMissile                     DOC   (15 cols)
 *   SpellMissileMotion               DOC   (5 cols)
 *   SpellReagents                    ACTIVE
 *   SpellVisual                      DOC   (26 cols)
 *   SpellVisualEffectName            DOC   (12 cols)
 *   SpellVisualKit                   DOC   (22 cols)
 *   SpellVisualKitAreaModel          DOC   (7 cols)
 *   SpellVisualKitModelAttach        DOC   (13 cols)
 *   SpellVisualMissile               DOC   (13 cols)
 *   Vignette                         DOC   (6 cols)
 *   WbAccessControlList              DOC   (6 cols)
 *   WbCertBlacklist                  DOC   (3 cols)
 *   WbCertWhitelist                  DOC   (7 cols)
 *   WbPermissions                    DOC   (3 cols)
 *
 *   (5 ACTIVE, 0 DORMANT, 53 DOC)
 *
 *   Worklist tables with no 5.4.8 client file (not catalogued above): NumTalentsAtLevel, SpellDifficulty, TalentTab, TalentTreePrimarySpells
 */

// BattlePetAbility -- 8 cols / 8 fields, record_size 32, build 5.4.8.18414. INERT reference (not modelled).
struct BattlePetAbilityEntry
{
    uint32   ID;  // c0 @0
    int32    FamilyId;  // c1 @4
    uint32   IconFileDataID;  // c2 @8
    uint32   Cooldown;  // c3 @12
    uint32   BattlePetVisualID;  // c4 @16
    uint32   Flags;  // c5 @20
    char*    Name_lang;  // c6 @24
    char*    Description_lang;  // c7 @28
};

// BattlePetAbilityEffect -- 7 cols / 12 fields, record_size 48, build 5.4.8.18414. INERT reference (not modelled).
struct BattlePetAbilityEffectEntry
{
    uint32   ID;  // c0 @0
    uint32   BattlePetAbilityTurnID;  // c1 @4
    uint32   BattlePetVisualID;  // c2 @8
    uint32   AuraBattlePetAbilityID;  // c3 @12
    uint32   BattlePetEffectPropertiesID;  // c4 @16
    uint32   OrderIndex;  // c5 @20
    int32    Param[6];  // c6 @24
};

// BattlePetAbilityState -- 4 cols / 4 fields, record_size 16, build 5.4.8.18414. INERT reference (not modelled).
struct BattlePetAbilityStateEntry
{
    uint32   ID;  // c0 @0
    uint32   BattlePetAbilityID;  // c1 @4
    uint32   BattlePetStateID;  // c2 @8
    int32    Value;  // c3 @12
};

// BattlePetAbilityTurn -- 6 cols / 6 fields, record_size 24, build 5.4.8.18414. INERT reference (not modelled).
struct BattlePetAbilityTurnEntry
{
    uint32   ID;  // c0 @0
    uint32   BattlePetAbilityID;  // c1 @4
    uint32   BattlePetVisualID;  // c2 @8
    uint32   Duration;  // [low-conf] c3 @12
    uint32   HasProcType;  // c4 @16
    int32    ProcType;  // c5 @20
};

// BattlePetBreedQuality -- 3 cols / 3 fields, record_size 12, build 5.4.8.18414. INERT reference (not modelled).
struct BattlePetBreedQualityEntry
{
    uint32   ID;  // c0 @0
    uint32   QualityEnum;  // c1 @4
    float    StateMultiplier;  // c2 @8
};

// BattlePetBreedState -- 4 cols / 4 fields, record_size 16, build 5.4.8.18414. INERT reference (not modelled).
struct BattlePetBreedStateEntry
{
    uint32   ID;  // c0 @0
    uint32   BattlePetBreedID;  // c1 @4
    uint32   BattlePetStateID;  // c2 @8
    int32    Value;  // c3 @12
};

// BattlePetEffectProperties -- 4 cols / 14 fields, record_size 56, build 5.4.8.18414. INERT reference (not modelled).
struct BattlePetEffectPropertiesEntry
{
    uint32   ID;  // c0 @0
    uint32   BattlePetVisualID;  // c1 @4
    char*    ParamLabel[6];  // c2 @8
    uint32   ParamTypeEnum[6];  // c3 @32
};

// BattlePetNPCTeamMember -- 2 cols / 2 fields, record_size 8, build 5.4.8.18414. INERT reference (not modelled).
struct BattlePetNPCTeamMemberEntry
{
    uint32   ID;  // c0 @0
    char*    Name_lang;  // c1 @4
};

// BattlePetSpecies -- 9 cols / 9 fields, record_size 36, build 5.4.8.18414. INERT reference (not modelled).
struct BattlePetSpeciesEntry
{
    uint32   ID;  // c0 @0
    uint32   CreatureID;  // c1 @4
    uint32   IconFileDataID;  // c2 @8
    uint32   SummonSpellID;  // c3 @12
    uint32   PetTypeEnum;  // c4 @16
    int32    SourceTypeEnum;  // c5 @20
    uint32   Flags;  // c6 @24
    char*    SourceText_lang;  // c7 @28
    char*    Description_lang;  // c8 @32
};

// BattlePetSpeciesState -- 4 cols / 4 fields, record_size 16, build 5.4.8.18414. INERT reference (not modelled).
struct BattlePetSpeciesStateEntry
{
    uint32   ID;  // c0 @0
    uint32   BattlePetSpeciesID;  // c1 @4
    uint32   BattlePetStateID;  // c2 @8
    int32    Value;  // c3 @12
};

// BattlePetSpeciesXAbility -- 5 cols / 5 fields, record_size 20, build 5.4.8.18414. INERT reference (not modelled).
struct BattlePetSpeciesXAbilityEntry
{
    uint32   ID;  // c0 @0
    uint32   BattlePetSpeciesID;  // c1 @4
    uint32   BattlePetAbilityID;  // c2 @8
    uint32   RequiredLevel;  // c3 @12
    uint32   SlotEnum;  // c4 @16
};

// BattlePetState -- 4 cols / 4 fields, record_size 16, build 5.4.8.18414. INERT reference (not modelled).
struct BattlePetStateEntry
{
    uint32   ID;  // c0 @0
    uint32   BattlePetVisualID;  // c1 @4
    char*    LuaName;  // c2 @8
    uint32   Flags;  // c3 @12
};

// BattlePetVisual -- 8 cols / 8 fields, record_size 32, build 5.4.8.18414. INERT reference (not modelled).
struct BattlePetVisualEntry
{
    uint32   ID;  // c0 @0
    uint32   SpellVisualID;  // c1 @4
    uint32   CastMilliSeconds;  // c2 @8
    uint32   ImpactMilliSeconds;  // c3 @12
    uint32   RangeTypeEnum;  // c4 @16
    uint32   Flags;  // c5 @20
    uint32   SceneScriptPackageID;  // c6 @24
    char*    SceneScriptFunction;  // c7 @28
};

// BroadcastText -- 9 cols / 13 fields, record_size 52, build 5.4.8.18414. INERT reference (not modelled).
struct BroadcastTextEntry
{
    uint32   ID;  // c0 @0
    uint32   LanguageID;  // c1 @4
    char*    Text_lang;  // c2 @8
    char*    Text1_lang;  // c3 @12
    uint32   EmoteID[3];  // c4 @16
    uint32   EmoteDelay[3];  // c5 @28
    uint32   SoundEntriesID;  // c6 @40
    uint32   EmotesID;  // c7 @44
    uint32   Flags;  // c8 @48
};

// Creature -- 10 cols / 18 fields, record_size 72, build 5.4.8.18414. INERT reference (not modelled).
struct CreatureEntry
{
    uint32   ID;  // c0 @0
    uint32   AlwaysItem[3];  // c1 @4
    uint32   MountCreatureID;  // c2 @16
    uint32   DisplayID[4];  // c3 @20
    float    DisplayProbability[4];  // c4 @36
    char*    Name_lang;  // c5 @52
    char*    Title_lang;  // c6 @56
    char*    TitleAlt_lang;  // [low-conf] c7 @60
    int32    Classification;  // c8 @64
    int32    StartAnimState;  // c9 @68
};

// CreatureDifficulty -- 7 cols / 11 fields, record_size 44, build 5.4.8.18414. INERT reference (not modelled).
struct CreatureDifficultyEntry
{
    uint32   ID;  // c0 @0
    uint32   CreatureID;  // c1 @4
    uint32   FactionTemplateID;  // c2 @8
    int32    ExpansionID;  // c3 @12
    int32    MinLevel;  // c4 @16
    int32    MaxLevel;  // c5 @20
    uint32   Flags[5];  // c6 @24
};

// Curve -- 3 cols / 3 fields, record_size 12, build 5.4.8.18414. INERT reference (not modelled).
struct CurveEntry
{
    uint32   ID;  // c0 @0
    uint32   Type;  // c1 @4
    uint32   Flags;  // c2 @8
};

// CurvePoint -- 4 cols / 5 fields, record_size 20, build 5.4.8.18414. INERT reference (not modelled).
struct CurvePointEntry
{
    uint32   ID;  // c0 @0
    uint32   CurveID;  // c1 @4
    uint32   OrderIndex;  // c2 @8
    float    Pos[2];  // c3 @12
};

// DeviceBlacklist -- 3 cols / 3 fields, record_size 12, build 5.4.8.18414. INERT reference (not modelled).
struct DeviceBlacklistEntry
{
    uint32   ID;  // c0 @0
    uint32   VendorID;  // c1 @4
    uint32   DeviceID;  // c2 @8
};

// DriverBlacklist -- 8 cols / 8 fields, record_size 32, build 5.4.8.18414. INERT reference (not modelled).
struct DriverBlacklistEntry
{
    uint32   ID;  // c0 @0
    uint32   VendorID;  // c1 @4
    uint32   DeviceID;  // c2 @8
    uint32   DriverVersionHi;  // c3 @12
    uint32   DriverVersionLow;  // c4 @16
    uint32   OsVersion;  // c5 @20
    uint32   OsBits;  // c6 @24
    uint32   Flags;  // c7 @28
};

// GameObjects -- 9 cols / 17 fields, record_size 68, build 5.4.8.18414. INERT reference (not modelled).
struct GameObjectsEntry
{
    uint32   ID;  // c0 @0
    uint32   OwnerID;  // c1 @4
    uint32   DisplayID;  // c2 @8
    float    Pos[3];  // c3 @12
    float    Rot[4];  // c4 @24
    float    Scale;  // c5 @40
    int32    TypeID;  // c6 @44
    int32    PropValue[4];  // c7 @48
    char*    Name_lang;  // c8 @64
};

// Item-sparse -- 68 cols / 134 fields, record_size 536, build 5.4.8.18414. INERT reference (not modelled).
struct Item_sparseEntry
{
    uint32   ID;  // c0 @0
    uint32   Quality;  // c1 @4
    uint32   Flags[3];  // c2 @8
    float    PriceRandomValue;  // c3 @20
    float    PriceVariance;  // c4 @24
    uint32   BuyCount;  // c5 @28
    uint32   BuyPrice;  // c6 @32
    uint32   SellPrice;  // c7 @36
    uint32   InventoryType;  // c8 @40
    int32    AllowableClass;  // c9 @44
    int32    AllowableRace;  // c10 @48
    uint32   ItemLevel;  // c11 @52
    int32    RequiredLevel;  // c12 @56
    uint32   RequiredSkill;  // c13 @60
    uint32   RequiredSkillRank;  // c14 @64
    uint32   RequiredSpell;  // c15 @68
    uint32   RequiredHonorRank;  // c16 @72
    uint32   RequiredCityRank;  // c17 @76
    uint32   RequiredReputationFaction;  // c18 @80
    uint32   RequiredReputationRank;  // c19 @84
    uint32   MaxCount;  // c20 @88
    uint32   Stackable;  // c21 @92
    uint32   ContainerSlots;  // c22 @96
    int32    ItemStatType[10];  // c23 @100
    int32    ItemStatValue[10];  // c24 @140
    int32    ItemScalingValue[10];  // c25 @180
    float    ItemSocketCostRate[10];  // c26 @220
    uint32   ScalingStatDistributionID;  // c27 @260
    uint32   DamageType;  // c28 @264
    uint32   Delay;  // c29 @268
    float    RangedModRange;  // c30 @272
    int32    SpellID[5];  // c31 @276
    int32    SpellTrigger[5];  // c32 @296
    int32    SpellCharges[5];  // c33 @316
    int32    SpellCooldown[5];  // c34 @336
    int32    SpellCategory[5];  // c35 @356
    int32    SpellCategoryCooldown[5];  // c36 @376
    uint32   Bonding;  // c37 @396
    char*    Display_lang;  // c38 @400
    char*    Display1_lang;  // c39 @404
    char*    Display2_lang;  // c40 @408
    char*    Display3_lang;  // c41 @412
    char*    Description_lang;  // c42 @416
    uint32   PageText;  // c43 @420
    uint32   LanguageID;  // c44 @424
    uint32   PageMaterialID;  // c45 @428
    uint32   StartQuest;  // c46 @432
    uint32   LockID;  // c47 @436
    int32    Material;  // c48 @440
    uint32   Sheath;  // c49 @444
    uint32   RandomProperty;  // c50 @448
    uint32   RandomSuffix;  // c51 @452
    uint32   ItemSet;  // c52 @456
    uint32   Area;  // c53 @460
    uint32   Map;  // c54 @464
    uint32   BagFamily;  // c55 @468
    uint32   TotemCategory;  // c56 @472
    uint32   Color[3];  // c57 @476
    uint32   Content[3];  // c58 @488
    int32    SocketBonus;  // c59 @500
    uint32   GemProperties;  // c60 @504
    float    ArmorDamageModifier;  // c61 @508
    uint32   Duration;  // c62 @512
    uint32   ItemLimitCategory;  // c63 @516
    uint32   HolidayID;  // c64 @520
    float    DmgVariance;  // c65 @524
    int32    CurrencySubstitutionID;  // c66 @528
    int32    CurrencySubstitutionCount;  // c67 @532
};

// ItemToBattlePet -- 2 cols / 2 fields, record_size 8, build 5.4.8.18414. INERT reference (not modelled).
struct ItemToBattlePetEntry
{
    uint32   ItemID;  // c0 @0
    uint32   SpeciesID;  // c1 @4
};

// ItemToMountSpell -- 2 cols / 2 fields, record_size 8, build 5.4.8.18414. INERT reference (not modelled).
struct ItemToMountSpellEntry
{
    uint32   ItemID;  // c0 @0
    uint32   SpellID;  // c1 @4
};

// ItemUpgrade -- 6 cols / 6 fields, record_size 24, build 5.4.8.18414. INERT reference (not modelled).
struct ItemUpgradeEntry
{
    uint32   ID;  // c0 @0
    uint32   ItemUpgradePathID;  // c1 @4
    uint32   ItemLevelBonus;  // c2 @8
    uint32   PrevItemUpgradeID;  // c3 @12
    uint32   CurrencyType;  // c4 @16
    uint32   CurrencyCost;  // c5 @20
};

// KeyChain -- 2 cols / 33 fields, record_size 36, build 5.4.8.18414. INERT reference (not modelled).
struct KeyChainEntry
{
    uint32   ID;  // c0 @0
    uint32   Key[8];  // c1 @4
};

// Locale -- 6 cols / 6 fields, record_size 24, build 5.4.8.18414. INERT reference (not modelled).
struct LocaleEntry
{
    uint32   ID;  // c0 @0
    uint32   Field_5_0_2_15827_001;  // c1 @4
    uint32   WowLocale;  // c2 @8
    uint32   Secondary;  // c3 @12
    uint32   FontFileDataID;  // c4 @16
    uint32   ClientDisplayExpansion;  // c5 @20
};

// Location -- 3 cols / 7 fields, record_size 28, build 5.4.8.18414. INERT reference (not modelled).
struct LocationEntry
{
    uint32   ID;  // c0 @0
    float    Pos[3];  // c1 @4
    float    Rot[3];  // c2 @16
};

// MapChallengeMode -- 6 cols / 10 fields, record_size 40, build 5.4.8.18414. INERT reference (not modelled).
struct MapChallengeModeEntry
{
    uint32   ID;  // c0 @0
    uint32   MapID;  // c1 @4
    uint32   Field02;  // c2 @8
    uint32   Field03;  // c3 @12
    uint32   Field04;  // c4 @16
    uint32   CriteriaCount[5];  // c5 @20
};

// MarketingPromotionsXLocale -- 8 cols / 8 fields, record_size 32, build 5.4.8.18414. INERT reference (not modelled).
struct MarketingPromotionsXLocaleEntry
{
    uint32   ID;  // c0 @0
    uint32   PromotionID;  // c1 @4
    int32    LocaleID;  // c2 @8
    uint32   AdTexture;  // c3 @12
    uint32   LogoTexture;  // c4 @16
    uint32   AcceptButtonTexture;  // c5 @20
    uint32   DeclineButtonTexture;  // c6 @24
    char*    AcceptURL;  // c7 @28
};

// Path -- 8 cols / 8 fields, record_size 32, build 5.4.8.18414. INERT reference (not modelled).
struct PathEntry
{
    uint32   ID;  // c0 @0
    uint32   Type;  // c1 @4
    uint32   SplineType;  // c2 @8
    uint32   Red;  // c3 @12
    uint32   Blue;  // c4 @16
    uint32   Green;  // c5 @20
    uint32   Alpha;  // c6 @24
    uint32   Flags;  // c7 @28
};

// PathNode -- 4 cols / 4 fields, record_size 16, build 5.4.8.18414. INERT reference (not modelled).
struct PathNodeEntry
{
    uint32   ID;  // c0 @0
    uint32   PathID;  // c1 @4
    uint32   Sequence;  // c2 @8
    uint32   LocationID;  // c3 @12
};

// PathNodeProperty -- 5 cols / 5 fields, record_size 20, build 5.4.8.18414. INERT reference (not modelled).
struct PathNodePropertyEntry
{
    uint32   ID;  // c0 @0
    uint32   PathID;  // c1 @4
    uint32   Sequence;  // c2 @8
    uint32   PropertyIndex;  // c3 @12
    int32    Value;  // c4 @16
};

// PathProperty -- 4 cols / 4 fields, record_size 16, build 5.4.8.18414. INERT reference (not modelled).
struct PathPropertyEntry
{
    uint32   ID;  // c0 @0
    uint32   PathID;  // c1 @4
    uint32   PropertyIndex;  // c2 @8
    int32    Value;  // c3 @12
};

// QuestPackageItem -- 5 cols / 5 fields, record_size 20, build 5.4.8.18414. INERT reference (not modelled).
struct QuestPackageItemEntry
{
    uint32   ID;  // c0 @0
    uint32   QuestPackageID;  // c1 @4
    uint32   ItemID;  // c2 @8
    uint32   ItemQuantity;  // c3 @12
    uint32   DisplayType;  // c4 @16
};

// RulesetItemUpgrade -- 4 cols / 4 fields, record_size 16, build 5.4.8.18414. INERT reference (not modelled).
struct RulesetItemUpgradeEntry
{
    uint32   ID;  // c0 @0
    uint32   RulesetID;  // c1 @4
    uint32   ItemUpgradeID;  // c2 @8
    uint32   ItemID;  // c3 @12
};

// RulesetRaidLootUpgrade -- 5 cols / 5 fields, record_size 20, build 5.4.8.18414. INERT reference (not modelled).
struct RulesetRaidLootUpgradeEntry
{
    uint32   ID;  // c0 @0
    uint32   Field_6_0_1_18179_001;  // c1 @4
    uint32   Field_6_0_1_18179_002;  // c2 @8
    uint32   ItemUpgradeID;  // c3 @12
    uint32   Field_6_0_1_18179_004;  // c4 @16
};

// SceneScriptPackage -- 2 cols / 2 fields, record_size 8, build 5.4.8.18414. INERT reference (not modelled).
struct SceneScriptPackageEntry
{
    uint32   ID;  // c0 @0
    char*    Name;  // c1 @4
};

// SceneScriptPackageMember -- 5 cols / 5 fields, record_size 20, build 5.4.8.18414. INERT reference (not modelled).
struct SceneScriptPackageMemberEntry
{
    uint32   ID;  // c0 @0
    uint32   SceneScriptPackageID;  // c1 @4
    uint32   SceneScriptID;  // c2 @8
    uint32   OrderIndex;  // c3 @12
    uint32   ChildSceneScriptPackageID;  // c4 @16
};

// SpellEffectCameraShakes -- 2 cols / 4 fields, record_size 16, build 5.4.8.18414. INERT reference (not modelled).
struct SpellEffectCameraShakesEntry
{
    uint32   ID;  // c0 @0
    uint32   CameraShake[3];  // c1 @4
};

// SpellMissile -- 15 cols / 15 fields, record_size 60, build 5.4.8.18414. INERT reference (not modelled).
struct SpellMissileEntry
{
    uint32   ID;  // c0 @0
    uint32   Flags;  // c1 @4
    float    DefaultPitchMin;  // c2 @8
    float    DefaultPitchMax;  // c3 @12
    float    DefaultSpeedMin;  // c4 @16
    float    DefaultSpeedMax;  // c5 @20
    float    RandomizeFacingMin;  // c6 @24
    float    RandomizeFacingMax;  // c7 @28
    float    RandomizePitchMin;  // c8 @32
    float    RandomizePitchMax;  // c9 @36
    float    RandomizeSpeedMin;  // c10 @40
    float    RandomizeSpeedMax;  // c11 @44
    float    Gravity;  // c12 @48
    float    MaxDuration;  // c13 @52
    float    CollisionRadius;  // c14 @56
};

// SpellMissileMotion -- 5 cols / 5 fields, record_size 20, build 5.4.8.18414. INERT reference (not modelled).
struct SpellMissileMotionEntry
{
    uint32   ID;  // c0 @0
    char*    Name;  // c1 @4
    char*    ScriptBody;  // c2 @8
    uint32   Flags;  // c3 @12
    uint32   MissileCount;  // c4 @16
};

// SpellVisual -- 26 cols / 30 fields, record_size 120, build 5.4.8.18414. INERT reference (not modelled).
struct SpellVisualEntry
{
    uint32   ID;  // c0 @0
    uint32   Field_5_0_1_15464_001;  // c1 @4
    uint32   PrecastKit;  // c2 @8
    uint32   CastKit;  // c3 @12
    uint32   ImpactKit;  // c4 @16
    uint32   StateKit;  // c5 @20
    uint32   StateDoneKit;  // c6 @24
    uint32   ChannelKit;  // c7 @28
    int32    MissileDestinationAttachment;  // c8 @32
    uint32   AnimEventSoundID;  // c9 @36
    uint32   Flags;  // c10 @40
    uint32   CasterImpactKit;  // c11 @44
    uint32   TargetImpactKit;  // c12 @48
    int32    MissileAttachment;  // c13 @52
    uint32   MissileMotion;  // c14 @56
    uint32   MissileTargetingKit;  // c15 @60
    uint32   InstantAreaKit;  // c16 @64
    uint32   ImpactAreaKit;  // c17 @68
    uint32   PersistentAreaKit;  // c18 @72
    float    MissileCastOffset[3];  // c19 @76
    float    MissileImpactOffset[3];  // c20 @88
    uint32   Field_5_4_0_17266_021;  // c21 @100
    uint32   Field_5_4_0_17266_022;  // c22 @104
    uint32   Field_5_4_0_17266_023;  // c23 @108
    uint32   Field_5_4_0_17266_024;  // c24 @112
    uint32   SpellVisualMissileSetID;  // c25 @116
};

// SpellVisualEffectName -- 12 cols / 9 fields, record_size 36, build 5.4.8.18414. INERT reference (not modelled).
struct SpellVisualEffectNameEntry
{
    uint32   ID;  // c0 @0
    char*    Name;  // c1 @4
    float    AreaEffectSize;  // c2 @8
    float    Scale;  // c3 @12
    float    MinAllowedScale;  // c4 @16
    float    MaxAllowedScale;  // c5 @20
    uint8    Type;  // c6 @24
    uint8    Padding0;  // c7 @25
    uint8    Padding1;  // c8 @26
    uint8    Padding2;  // c9 @27
    float    Alpha;  // c10 @28
    uint32   Flags;  // c11 @32
};

// SpellVisualKit -- 22 cols / 39 fields, record_size 156, build 5.4.8.18414. INERT reference (not modelled).
struct SpellVisualKitEntry
{
    uint32   ID;  // c0 @0
    int32    StartAnimID;  // c1 @4
    int32    AnimID;  // c2 @8
    uint32   AnimKitID;  // c3 @12
    uint32   HeadEffect;  // c4 @16
    uint32   ChestEffect;  // c5 @20
    uint32   BaseEffect;  // c6 @24
    uint32   LeftHandEffect;  // c7 @28
    uint32   RightHandEffect;  // c8 @32
    uint32   BreathEffect;  // c9 @36
    uint32   LeftWeaponEffect;  // c10 @40
    uint32   RightWeaponEffect;  // c11 @44
    uint32   SpecialEffect[3];  // c12 @48
    uint32   WorldEffect;  // c13 @60
    uint32   SoundID;  // c14 @64
    uint32   ShakeID;  // c15 @68
    int32    CharProc[4];  // c16 @72
    float    CharParamZero[4];  // c17 @88
    float    CharParamOne[4];  // c18 @104
    float    CharParamTwo[4];  // c19 @120
    float    CharParamThree[4];  // c20 @136
    uint32   Flags;  // c21 @152
};

// SpellVisualKitAreaModel -- 7 cols / 7 fields, record_size 28, build 5.4.8.18414. INERT reference (not modelled).
struct SpellVisualKitAreaModelEntry
{
    uint32   ID;  // c0 @0
    uint32   ModelFileDataID;  // c1 @4
    uint32   Flags;  // c2 @8
    uint32   LifeTime;  // c3 @12
    float    EmissionRate;  // c4 @16
    float    Spacing;  // c5 @20
    float    ModelScale;  // c6 @24
};

// SpellVisualKitModelAttach -- 13 cols / 15 fields, record_size 60, build 5.4.8.18414. INERT reference (not modelled).
struct SpellVisualKitModelAttachEntry
{
    uint32   ID;  // c0 @0
    uint32   ParentSpellVisualKitID;  // c1 @4
    uint32   SpellVisualEffectNameID;  // c2 @8
    int32    AttachmentID;  // c3 @12
    float    Offset[3];  // c4 @16
    float    Yaw;  // c5 @28
    float    Pitch;  // c6 @32
    float    Roll;  // c7 @36
    uint32   Field_4_0_6_13623_008;  // c8 @40
    int32    StartAnimID;  // c9 @44
    int32    AnimID;  // c10 @48
    int32    EndAnimID;  // c11 @52
    uint32   AnimKitID;  // c12 @56
};

// SpellVisualMissile -- 13 cols / 17 fields, record_size 68, build 5.4.8.18414. INERT reference (not modelled).
struct SpellVisualMissileEntry
{
    uint32   ID;  // c0 @0
    uint32   SpellVisualMissileSetID;  // c1 @4
    uint32   SpellVisualEffectNameID;  // c2 @8
    int32    DestinationAttachment;  // c3 @12
    uint32   SoundEntriesID;  // c4 @16
    int32    Attachment;  // c5 @20
    int32    Field_5_4_0_17266_006;  // c6 @24
    int32    FollowGroundDropSpeed;  // c7 @28
    int32    FollowGroundApproach;  // c8 @32
    uint32   Flags;  // c9 @36
    uint32   SpellMissileMotionID;  // c10 @40
    float    ImpactOffset[3];  // c11 @44
    float    CastOffset[3];  // c12 @56
};

// Vignette -- 6 cols / 6 fields, record_size 24, build 5.4.8.18414. INERT reference (not modelled).
struct VignetteEntry
{
    uint32   ID;  // c0 @0
    char*    Name_lang;  // c1 @4
    uint32   QuestFeedbackEffectID;  // c2 @8
    uint32   Flags;  // c3 @12
    float    MaxHeight;  // c4 @16
    float    MinHeight;  // c5 @20
};

// WbAccessControlList -- 6 cols / 6 fields, record_size 24, build 5.4.8.18414. INERT reference (not modelled).
struct WbAccessControlListEntry
{
    uint32   ID;  // c0 @0
    char*    URL;  // c1 @4
    uint32   GrantFlags;  // c2 @8
    uint32   RevokeFlags;  // c3 @12
    int32    WowEditInternal;  // c4 @16
    uint32   RegionFlags;  // c5 @20
};

// WbCertBlacklist -- 3 cols / 22 fields, record_size 28, build 5.4.8.18414. INERT reference (not modelled).
struct WbCertBlacklistEntry
{
    uint32   ID;  // c0 @0
    char*    Field_5_3_0_16965_001;  // c1 @4
    uint32   Field_5_3_0_16965_002[5];  // [low-conf] c2 @8
};

// WbCertWhitelist -- 7 cols / 5 fields, record_size 16, build 5.4.8.18414. INERT reference (not modelled).
struct WbCertWhitelistEntry
{
    uint32   ID;  // c0 @0
    char*    Domain;  // c1 @4
    int8     GrantAccess;  // c2 @8
    int8     RevokeAccess;  // c3 @9
    int8     Padding_5_3_0_16965_004_0;  // c4 @10
    int8     Padding_5_3_0_16965_004_1;  // c5 @11
    int32    WowEditInternal;  // c6 @12
};

// WbPermissions -- 3 cols / 3 fields, record_size 12, build 5.4.8.18414. INERT reference (not modelled).
struct WbPermissionsEntry
{
    uint32   ID;  // c0 @0
    char*    Filename;  // c1 @4
    uint32   Permissions;  // c2 @8
};

#endif
