file(READ "${SOURCE_ROOT}/src/game/Object/Player.h" player_header)
file(READ "${SOURCE_ROOT}/src/game/WorldHandlers/CharacterHandlerCustomize.cpp" customize_handler)
file(READ "${SOURCE_ROOT}/src/game/Server/Opcodes.cpp" opcode_registry)
file(READ "${SOURCE_ROOT}/src/game/Server/Opcodes.h" opcode_header)
file(READ "${SOURCE_ROOT}/src/game/Server/WorldSession.cpp" world_session)

if(MUTATION STREQUAL "request_reader")
    string(REPLACE "MopCharacterCustomizePackets::ReadRequest(recv_data)" "MopCharacterCustomizePackets::Request()" customize_handler "${customize_handler}")
elseif(MUTATION STREQUAL "success_builder")
    string(REPLACE "BuildResponse(data, RESPONSE_SUCCESS, guid," "BuildResponse(data, CHAR_CREATE_ERROR, guid," customize_handler "${customize_handler}")
elseif(MUTATION STREQUAL "error_builder")
    string(REPLACE "BuildResponse(data, result, guid," "BuildResponse(data, RESPONSE_SUCCESS, guid," customize_handler "${customize_handler}")
elseif(MUTATION STREQUAL "client_registration")
    string(REPLACE "DefC(CMSG_CHAR_CUSTOMIZE," "DefC(CMSG_UNUSED_CHAR_CUSTOMIZE," opcode_registry "${opcode_registry}")
elseif(MUTATION STREQUAL "server_registration")
    string(REPLACE "DefS(SMSG_CHAR_CUSTOMIZE," "DefS(SMSG_UNUSED_CHAR_CUSTOMIZE," opcode_registry "${opcode_registry}")
elseif(MUTATION STREQUAL "whitelist")
    string(REPLACE "case SMSG_CHAR_CUSTOMIZE:" "case SMSG_UNUSED_CHAR_CUSTOMIZE:" world_session "${world_session}")
elseif(MUTATION STREQUAL "client_value")
    string(REPLACE "CMSG_CHAR_CUSTOMIZE                          = 0x0A13" "CMSG_CHAR_CUSTOMIZE                          = 0x0000" opcode_header "${opcode_header}")
elseif(MUTATION STREQUAL "server_value")
    string(REPLACE "SMSG_CHAR_CUSTOMIZE                          = 0x1432" "SMSG_CHAR_CUSTOMIZE                          = 0x0000" opcode_header "${opcode_header}")
endif()

string(FIND "${customize_handler}" "MopCharacterCustomizePackets::ReadRequest(recv_data)" request_reader)
if(request_reader EQUAL -1)
    message(FATAL_ERROR "character customization handler bypasses the 18414 request reader")
endif()
string(FIND "${customize_handler}" "BuildResponse(data, RESPONSE_SUCCESS, guid," success_builder)
if(success_builder EQUAL -1)
    message(FATAL_ERROR "character customization success bypasses the 18414 response builder")
endif()
string(FIND "${customize_handler}" "BuildResponse(data, result, guid," error_builder)
if(error_builder EQUAL -1)
    message(FATAL_ERROR "character customization errors bypass the 18414 response builder")
endif()
string(FIND "${customize_handler}" "WorldPacket data(SMSG_CHAR_CUSTOMIZE, 1)" legacy_error)
if(NOT legacy_error EQUAL -1)
    message(FATAL_ERROR "legacy one-byte character customization error remains")
endif()
string(FIND "${customize_handler}" "data << ObjectGuid(guid)" legacy_success)
if(NOT legacy_success EQUAL -1)
    message(FATAL_ERROR "legacy flat character customization response remains")
endif()
string(FIND "${player_header}" "in.ReadGuidMask<2, 6, 1, 0, 7, 5>(request.guid)" request_layout)
if(request_layout EQUAL -1)
    message(FATAL_ERROR "18414 character customization request layout is missing")
endif()
string(FIND "${player_header}" "out.WriteGuidMask<0, 7, 3, 2, 6, 5, 1, 4>(guid)" response_layout)
if(response_layout EQUAL -1)
    message(FATAL_ERROR "18414 character customization response layout is missing")
endif()
string(FIND "${opcode_registry}" "DefC(CMSG_CHAR_CUSTOMIZE, \"CMSG_CHAR_CUSTOMIZE\"" client_registration)
if(client_registration EQUAL -1)
    message(FATAL_ERROR "CMSG_CHAR_CUSTOMIZE is not registered")
endif()
string(FIND "${opcode_registry}" "DefS(SMSG_CHAR_CUSTOMIZE, \"SMSG_CHAR_CUSTOMIZE\")" server_registration)
if(server_registration EQUAL -1)
    message(FATAL_ERROR "SMSG_CHAR_CUSTOMIZE is missing outbound metadata")
endif()
string(FIND "${world_session}" "case SMSG_CHAR_CUSTOMIZE:" whitelist)
if(whitelist EQUAL -1)
    message(FATAL_ERROR "SMSG_CHAR_CUSTOMIZE is not admitted through send suppression")
endif()
string(FIND "${opcode_header}" "CMSG_CHAR_CUSTOMIZE                          = 0x0A13" client_value)
if(client_value EQUAL -1)
    message(FATAL_ERROR "CMSG_CHAR_CUSTOMIZE value drifted")
endif()
string(FIND "${opcode_header}" "SMSG_CHAR_CUSTOMIZE                          = 0x1432" server_value)
if(server_value EQUAL -1)
    message(FATAL_ERROR "SMSG_CHAR_CUSTOMIZE value drifted")
endif()
