file(READ "${SOURCE_ROOT}/src/game/Object/Player.cpp" player_cpp)
file(READ "${SOURCE_ROOT}/src/game/WorldHandlers/SkillHandler.cpp" skill_cpp)
file(READ "${SOURCE_ROOT}/src/game/Server/Opcodes.cpp" opcode_cpp)
file(READ "${SOURCE_ROOT}/src/game/Server/Opcodes.h" opcode_h)

function(strip_cpp_comments output source)
    string(REGEX REPLACE "/\\*([^*]|\\*[^/])*\\*/" "" text "${source}")
    string(REGEX REPLACE "//[^\r\n]*" "" text "${text}")
    set(${output} "${text}" PARENT_SCOPE)
endfunction()

strip_cpp_comments(player_cpp "${player_cpp}")
strip_cpp_comments(skill_cpp "${skill_cpp}")
strip_cpp_comments(opcode_cpp "${opcode_cpp}")

foreach(source IN ITEMS player_cpp skill_cpp)
    string(FIND "${${source}}" "MopRespecPackets::BuildRespecWipeConfirm" builder)
    if(builder EQUAL -1)
        message(FATAL_ERROR "${source}: missing respec prompt builder")
    endif()
endforeach()

string(FIND "${skill_cpp}" "MopRespecPackets::ReadConfirmRespecWipe" parser)
if(parser EQUAL -1)
    message(FATAL_ERROR "SkillHandler.cpp: missing respec confirm parser")
endif()
string(FIND "${skill_cpp}" "confirm.discriminator != 0" reject)
if(reject EQUAL -1)
    message(FATAL_ERROR "SkillHandler.cpp: missing nonzero-discriminator reject")
endif()

string(FIND "${player_cpp}" "MSG_TALENT_WIPE_CONFIRM" player_legacy)
string(FIND "${skill_cpp}" "MSG_TALENT_WIPE_CONFIRM" skill_legacy)
if(NOT player_legacy EQUAL -1 OR NOT skill_legacy EQUAL -1)
    message(FATAL_ERROR "live legacy MSG_TALENT_WIPE_CONFIRM construction remains")
endif()

string(REGEX REPLACE "[ \t\r\n]+" " " normalized_opcode "${opcode_cpp}")
set(inbound "DefC(CMSG_CONFIRM_RESPEC_WIPE, \"CMSG_CONFIRM_RESPEC_WIPE\", STATUS_LOGGEDIN, PROCESS_THREADUNSAFE, &WorldSession::HandleTalentWipeConfirmOpcode);")
set(outbound "DefS(SMSG_RESPEC_WIPE_CONFIRM, \"SMSG_RESPEC_WIPE_CONFIRM\");")
string(FIND "${normalized_opcode}" "${inbound}" inbound_found)
string(FIND "${normalized_opcode}" "${outbound}" outbound_found)
if(inbound_found EQUAL -1 OR outbound_found EQUAL -1)
    message(FATAL_ERROR "missing Wave 13 opcode registration")
endif()
string(FIND "${opcode_h}" "CMSG_CONFIRM_RESPEC_WIPE" inbound_enum)
if(inbound_enum EQUAL -1)
    message(FATAL_ERROR "missing CMSG_CONFIRM_RESPEC_WIPE enum")
endif()
