file(READ "${SOURCE_ROOT}/src/game/WorldHandlers/ItemHandlerVendor.cpp" vendor_handler)
file(READ "${SOURCE_ROOT}/src/game/Server/Opcodes.cpp" opcode_registry)
file(READ "${SOURCE_ROOT}/src/game/Server/Opcodes.h" opcode_header)
file(READ "${SOURCE_ROOT}/src/game/Server/WorldSession.cpp" world_session)

if(MUTATION STREQUAL "request_reader")
    string(REPLACE "MopItemPackets::ReadListInventory(recv_data)" "ObjectGuid()" vendor_handler "${vendor_handler}")
elseif(MUTATION STREQUAL "response_builder")
    string(REPLACE "MopItemPackets::BuildVendorList(data, vendorList)" "data.Initialize(SMSG_LIST_INVENTORY)" vendor_handler "${vendor_handler}")
elseif(MUTATION STREQUAL "client_registration")
    string(REPLACE "DefC(CMSG_LIST_INVENTORY," "DefC(CMSG_UNUSED_LIST_INVENTORY," opcode_registry "${opcode_registry}")
elseif(MUTATION STREQUAL "server_registration")
    string(REPLACE "DefS(SMSG_LIST_INVENTORY," "DefS(SMSG_UNUSED_LIST_INVENTORY," opcode_registry "${opcode_registry}")
elseif(MUTATION STREQUAL "whitelist")
    string(REPLACE "case SMSG_LIST_INVENTORY:" "case SMSG_UNUSED_LIST_INVENTORY:" world_session "${world_session}")
endif()

string(FIND "${vendor_handler}" "MopItemPackets::ReadListInventory(recv_data)" request_reader)
if(request_reader EQUAL -1)
    message(FATAL_ERROR "vendor list handler bypasses the 18414 request reader")
endif()
string(FIND "${vendor_handler}" "MopItemPackets::BuildVendorList(data, vendorList)" response_builder)
if(response_builder EQUAL -1)
    message(FATAL_ERROR "vendor list sender bypasses the 18414 response builder")
endif()
string(FIND "${vendor_handler}" "data.WriteBits(count, 21)" legacy_count)
if(NOT legacy_count EQUAL -1)
    message(FATAL_ERROR "legacy 21-bit vendor item count remains")
endif()
string(FIND "${opcode_registry}" "DefC(CMSG_LIST_INVENTORY, \"CMSG_LIST_INVENTORY\"" client_registration)
if(client_registration EQUAL -1)
    message(FATAL_ERROR "CMSG_LIST_INVENTORY is not registered")
endif()
string(FIND "${opcode_registry}" "DefS(SMSG_LIST_INVENTORY, \"SMSG_LIST_INVENTORY\")" server_registration)
if(server_registration EQUAL -1)
    message(FATAL_ERROR "SMSG_LIST_INVENTORY is missing outbound metadata")
endif()
string(FIND "${world_session}" "case SMSG_LIST_INVENTORY:" whitelist)
if(whitelist EQUAL -1)
    message(FATAL_ERROR "SMSG_LIST_INVENTORY is not admitted through send suppression")
endif()
string(FIND "${opcode_header}" "CMSG_LIST_INVENTORY                          = 0x02D8" client_value)
if(client_value EQUAL -1)
    message(FATAL_ERROR "CMSG_LIST_INVENTORY value drifted")
endif()
string(FIND "${opcode_header}" "SMSG_LIST_INVENTORY                          = 0x1AAE" server_value)
if(server_value EQUAL -1)
    message(FATAL_ERROR "SMSG_LIST_INVENTORY value drifted")
endif()
