file(READ "${SOURCE_ROOT}/src/game/Object/Player.cpp" player)
file(READ "${SOURCE_ROOT}/src/game/Object/Player.h" player_header)
file(READ "${SOURCE_ROOT}/src/game/Object/PlayerActionButton.cpp" action_buttons)
file(READ "${SOURCE_ROOT}/src/game/Object/ReputationMgr.cpp" reputation)
file(READ "${SOURCE_ROOT}/src/game/Server/WorldSession.cpp" world_session)
file(READ "${SOURCE_ROOT}/src/game/WorldHandlers/WorldSessionMgr.cpp" world_session_mgr)
file(READ "${SOURCE_ROOT}/src/game/WorldHandlers/CharacterHandler.cpp" character_handler)
file(READ "${SOURCE_ROOT}/src/game/WorldHandlers/AchievementMgr.cpp" achievement)
file(READ "${SOURCE_ROOT}/src/game/WorldHandlers/Weather.cpp" weather)
file(READ "${SOURCE_ROOT}/src/game/WorldHandlers/SpellEffectTail.cpp" spell_effect)
file(READ "${SOURCE_ROOT}/src/game/Server/Opcodes.cpp" opcode_registry)
file(READ "${SOURCE_ROOT}/src/game/Server/opcode_register.inc" login_registry)

function(extract_body output source start_marker end_marker)
    string(FIND "${source}" "${start_marker}" start)
    string(FIND "${source}" "${end_marker}" end)
    if(start EQUAL -1 OR end EQUAL -1 OR NOT start LESS end)
        message(FATAL_ERROR "Could not isolate ${start_marker}")
    endif()
    math(EXPR length "${end} - ${start}")
    string(SUBSTRING "${source}" ${start} ${length} body)
    set(${output} "${body}" PARENT_SCOPE)
endfunction()

extract_body(initial_spells "${player}" "void Player::SendInitialSpells()" "void Player::_SetCreateBits")
extract_body(proficiency "${player}" "void Player::SendProficiency(" "void Player::RemovePetitionsAndSigns")
extract_body(initial_before_map "${player}" "void Player::SendInitialPacketsBeforeAddToMap()" "void Player::SendInitialPacketsAfterAddToMap()")
extract_body(initial_actions "${action_buttons}" "void Player::SendInitialActionButtons()" "void Player::SendLockActionButtons()")
extract_body(lock_actions "${action_buttons}" "void Player::SendLockActionButtons()" "bool Player::IsActionButtonDataValid")
extract_body(account_times "${world_session}" "void WorldSession::SendAccountDataTimes(" "void WorldSession::LoadTutorialsData")
extract_body(tutorials "${world_session}" "void WorldSession::SendTutorialsData()" "void WorldSession::SaveTutorialsData")
extract_body(player_login "${character_handler}" "void WorldSession::HandlePlayerLogin(LoginQueryHolder* holder)" "void WorldSession::HandleSetFactionAtWarOpcode")
extract_body(initial_reputation "${reputation}" "void ReputationMgr::SendInitialReputations()" "void ReputationMgr::SendVisible")
extract_body(all_achievements "${achievement}" "void AchievementMgr::SendAllAchievementData()" "void AchievementMgr::SendRespondInspectAchievements")
extract_body(single_weather "${weather}" "void Weather::SendWeatherUpdateToPlayer(" "bool Weather::SendWeatherForPlayersInZone")
extract_body(zone_weather "${weather}" "bool Weather::SendWeatherForPlayersInZone(" "void Weather::SetWeather")
extract_body(bind_spell "${spell_effect}" "void Spell::EffectBind(" "void Spell::EffectRestoreItemCharges")

if(initial_spells MATCHES "GetSpellCooldownMap|put<uint16>|<<[ \t]*uint16\(0\)")
    message(FATAL_ERROR "legacy INITIAL_SPELLS slot/cooldown body remains")
endif()
string(FIND "${initial_before_map}" "    data.Initialize(SMSG_SEND_UNLEARN_SPELLS, 4);" legacy_unlearn)
if(NOT legacy_unlearn EQUAL -1)
    message(FATAL_ERROR "legacy uint32 SEND_UNLEARN_SPELLS count remains")
endif()
if(initial_actions MATCHES "MAX_ACTION_BUTTONS[ \t]*[*][ \t]*4|packedData")
    message(FATAL_ERROR "legacy 144-uint32 ACTION_BUTTONS body remains")
endif()
if(lock_actions MATCHES "WorldPacket[ \t]+data\(SMSG_ACTION_BUTTONS,[ \t]*1\)|data[ \t]*<<[ \t]*uint8\(2\)")
    message(FATAL_ERROR "legacy one-byte lock body remains")
endif()
if(initial_reputation MATCHES "0x00000100")
    message(FATAL_ERROR "legacy INITIALIZE_FACTIONS leading 0x100 remains")
endif()
if(player_login MATCHES "data[ \t]*<<[ \t]*uint8\(2\)[^\n]*status")
    message(FATAL_ERROR "legacy FEATURE_SYSTEM_STATUS field sequence remains")
endif()
string(FIND "${initial_before_map}" "    data << m_homebindZ;" legacy_login_bind)
string(FIND "${bind_spell}" "    data << float(loc.coord_x);" legacy_spell_bind)
if(NOT legacy_login_bind EQUAL -1 OR NOT legacy_spell_bind EQUAL -1)
    message(FATAL_ERROR "inline or incorrectly ordered BINDPOINTUPDATE body remains")
endif()
if(single_weather MATCHES "uint8\(0\)" OR zone_weather MATCHES "uint8\(0\)")
    message(FATAL_ERROR "legacy byte WEATHER flag remains")
endif()
string(FIND "${all_achievements}" "data.WriteBits(m_criteriaProgress.size(), 21);" legacy_progress_count)
string(FIND "${all_achievements}" "data.WriteBits(m_completedAchievements.size(), 23);" legacy_completed_count)
if(NOT legacy_progress_count EQUAL -1 OR NOT legacy_completed_count EQUAL -1)
    message(FATAL_ERROR "legacy 21/23-bit ALL_ACHIEVEMENT_DATA counts remain")
endif()

if(NOT initial_spells MATCHES "MopInitialPackets::BuildInitialSpells")
    message(FATAL_ERROR "BuildInitialSpells is not used by its production sender")
endif()
if(NOT initial_before_map MATCHES "MopInitialPackets::BuildSendUnlearnSpells")
    message(FATAL_ERROR "BuildSendUnlearnSpells is not used by its production sender")
endif()
if(NOT initial_actions MATCHES "MopInitialPackets::BuildActionButtons" OR
   NOT lock_actions MATCHES "MopInitialPackets::BuildActionButtons")
    message(FATAL_ERROR "BuildActionButtons is not used by both production senders")
endif()
if(NOT account_times MATCHES "MopInitialPackets::BuildAccountDataTimes")
    message(FATAL_ERROR "BuildAccountDataTimes is not used by its production sender")
endif()
if(NOT player_login MATCHES "MopInitialPackets::BuildFeatureSystemStatus")
    message(FATAL_ERROR "BuildFeatureSystemStatus is not used by its production sender")
endif()
if(NOT initial_reputation MATCHES "MopInitialPackets::BuildInitializeFactions")
    message(FATAL_ERROR "BuildInitializeFactions is not used by its production sender")
endif()
if(NOT tutorials MATCHES "MopInitialPackets::BuildTutorialFlags")
    message(FATAL_ERROR "BuildTutorialFlags is not used by its production sender")
endif()
if(NOT initial_before_map MATCHES "MopInitialPackets::BuildBindPointUpdate" OR
   NOT bind_spell MATCHES "MopInitialPackets::BuildBindPointUpdate")
    message(FATAL_ERROR "BuildBindPointUpdate is not used by both production senders")
endif()
if(NOT proficiency MATCHES "MopInitialPackets::BuildSetProficiency")
    message(FATAL_ERROR "BuildSetProficiency is not used by its production sender")
endif()
if(NOT single_weather MATCHES "MopInitialPackets::BuildWeather" OR
   NOT zone_weather MATCHES "MopInitialPackets::BuildWeather")
    message(FATAL_ERROR "BuildWeather is not used by both production senders")
endif()
if(NOT all_achievements MATCHES "MopAchievementPackets::BuildAllAchievementData")
    message(FATAL_ERROR "BuildAllAchievementData is not used by its production sender")
endif()

foreach(call IN ITEMS
        "SendInitialSpells()"
        "MopInitialPackets::BuildSendUnlearnSpells"
        "SendInitialActionButtons()"
        "m_reputationMgr.SendInitialReputations()"
        "m_achievementMgr.SendAllAchievementData()"
        "MopInitialPackets::BuildBindPointUpdate")
    if(NOT initial_before_map MATCHES "${call}")
        message(FATAL_ERROR "${call} left SendInitialPacketsBeforeAddToMap")
    endif()
endforeach()
foreach(call IN ITEMS
        "SendAccountDataTimes(PER_CHARACTER_CACHE_MASK)"
        "MopInitialPackets::BuildFeatureSystemStatus"
        "SendInitialPacketsBeforeAddToMap()"
        "SendInitialPacketsAfterAddToMap()")
    string(FIND "${player_login}" "${call}" login_call)
    if(login_call EQUAL -1)
        message(FATAL_ERROR "${call} left the character login envelope")
    endif()
endforeach()
if(NOT world_session_mgr MATCHES "s->SendTutorialsData\(\)" OR
   NOT world_session_mgr MATCHES "pop_sess->SendTutorialsData\(\)")
    message(FATAL_ERROR "tutorial flags left the authenticated session phase")
endif()

if(NOT player_header MATCHES "#[ \t]*define[ \t]+MAX_ACTION_BUTTONS[ \t]+144")
    message(FATAL_ERROR "MAX_ACTION_BUTTONS changed")
endif()
if(NOT EXISTS "${SOURCE_ROOT}/src/game/Server/MopInitialPackets.h")
    message(FATAL_ERROR "MopInitialPackets.h is missing")
endif()
if(NOT EXISTS "${SOURCE_ROOT}/src/game/Server/MopAchievementPackets.h")
    message(FATAL_ERROR "MopAchievementPackets.h is missing")
endif()
file(READ "${SOURCE_ROOT}/src/game/Server/MopInitialPackets.h" initial_header)
if(NOT initial_header MATCHES "ACTION_BUTTON_COUNT[ \t]*=[ \t]*132")
    message(FATAL_ERROR "wire ACTION_BUTTON_COUNT is not 132")
endif()

foreach(server_name IN ITEMS
        SMSG_INITIAL_SPELLS
        SMSG_SEND_UNLEARN_SPELLS
        SMSG_ACTION_BUTTONS
        SMSG_INITIALIZE_FACTIONS
        SMSG_ALL_ACHIEVEMENT_DATA
        SMSG_BINDPOINTUPDATE
        SMSG_SET_PROFICIENCY
        SMSG_WEATHER)
    string(REGEX MATCHALL "DefS\\(${server_name},[ \t]*\"${server_name}\"\\)" registry_matches "${opcode_registry}")
    list(LENGTH registry_matches registry_count)
    if(NOT registry_count EQUAL 1)
        message(FATAL_ERROR "${server_name} must have exactly one outbound metadata row in Opcodes.cpp")
    endif()
endforeach()

foreach(server_name IN ITEMS
        SMSG_ACCOUNT_DATA_TIMES
        SMSG_FEATURE_SYSTEM_STATUS
        SMSG_TUTORIAL_FLAGS)
    string(REGEX MATCHALL "DefS\\(${server_name},[ \t]*\"${server_name}\"\\)" login_matches "${login_registry}")
    list(LENGTH login_matches login_count)
    if(NOT login_count EQUAL 1)
        message(FATAL_ERROR "${server_name} must remain registered exactly once in opcode_register.inc")
    endif()
    if(opcode_registry MATCHES "DefS\\(${server_name},[ \t]*\"${server_name}\"\\)")
        message(FATAL_ERROR "${server_name} is duplicated in Opcodes.cpp")
    endif()
endforeach()
