file(READ "${SOURCE_ROOT}/src/game/WorldHandlers/NPCHandler.cpp" npc_handler)
file(READ "${SOURCE_ROOT}/src/game/WorldHandlers/GossipDef.cpp" gossip_def)
file(READ "${SOURCE_ROOT}/src/game/Server/Opcodes.cpp" opcode_registry)
file(READ "${SOURCE_ROOT}/src/game/Server/Opcodes.h" opcode_header)
file(READ "${SOURCE_ROOT}/src/game/Server/WorldSession.cpp" world_session)

if(MUTATION STREQUAL "request_reader")
    string(REPLACE "MopGossipPackets::ReadHello(recv_data)" "ObjectGuid()" npc_handler "${npc_handler}")
elseif(MUTATION STREQUAL "response_builder")
    string(REPLACE "MopGossipPackets::BuildMessage(data, message)" "data.Initialize(SMSG_GOSSIP_MESSAGE)" gossip_def "${gossip_def}")
elseif(MUTATION STREQUAL "client_registration")
    string(REPLACE "DefC(CMSG_GOSSIP_HELLO," "DefC(CMSG_UNUSED_GOSSIP_HELLO," opcode_registry "${opcode_registry}")
elseif(MUTATION STREQUAL "server_registration")
    string(REPLACE "DefS(SMSG_GOSSIP_MESSAGE," "DefS(SMSG_UNUSED_GOSSIP_MESSAGE," opcode_registry "${opcode_registry}")
elseif(MUTATION STREQUAL "whitelist")
    string(REPLACE "case SMSG_GOSSIP_MESSAGE:" "case SMSG_UNUSED_GOSSIP_MESSAGE:" world_session "${world_session}")
endif()

string(FIND "${npc_handler}" "MopGossipPackets::ReadHello(recv_data)" request_reader)
if(request_reader EQUAL -1)
    message(FATAL_ERROR "gossip hello handler bypasses the 18414 request reader")
endif()
string(FIND "${gossip_def}" "MopGossipPackets::BuildMessage(data, message)" response_builder)
if(response_builder EQUAL -1)
    message(FATAL_ERROR "gossip menu sender bypasses the 18414 response builder")
endif()
string(FIND "${gossip_def}" "data << ObjectGuid(objectGuid)" legacy_guid)
if(NOT legacy_guid EQUAL -1)
    message(FATAL_ERROR "legacy flat gossip GUID serialization remains")
endif()
string(FIND "${opcode_registry}" "DefC(CMSG_GOSSIP_HELLO, \"CMSG_GOSSIP_HELLO\"" client_registration)
if(client_registration EQUAL -1)
    message(FATAL_ERROR "CMSG_GOSSIP_HELLO is not registered")
endif()
string(FIND "${opcode_registry}" "DefS(SMSG_GOSSIP_MESSAGE, \"SMSG_GOSSIP_MESSAGE\")" server_registration)
if(server_registration EQUAL -1)
    message(FATAL_ERROR "SMSG_GOSSIP_MESSAGE is missing outbound metadata")
endif()
string(FIND "${world_session}" "case SMSG_GOSSIP_MESSAGE:" whitelist)
if(whitelist EQUAL -1)
    message(FATAL_ERROR "SMSG_GOSSIP_MESSAGE is not admitted through send suppression")
endif()
string(FIND "${opcode_header}" "CMSG_GOSSIP_HELLO                            = 0x12F3" client_value)
if(client_value EQUAL -1)
    message(FATAL_ERROR "CMSG_GOSSIP_HELLO value drifted")
endif()
string(FIND "${opcode_header}" "SMSG_GOSSIP_MESSAGE                          = 0x0244" server_value)
if(server_value EQUAL -1)
    message(FATAL_ERROR "SMSG_GOSSIP_MESSAGE value drifted")
endif()
