file(READ "${SOURCE_ROOT}/src/game/WorldHandlers/SpellPackets.cpp" spell_packets)
file(READ "${SOURCE_ROOT}/src/game/Object/Unit.cpp" unit_cpp)
file(READ "${SOURCE_ROOT}/src/game/Server/Opcodes.cpp" opcodes_cpp)
file(READ "${SOURCE_ROOT}/src/game/Server/Opcodes.h" opcodes_h)
file(READ "${SOURCE_ROOT}/src/game/Server/Opcodes_reference.h" opcode_reference)
file(READ "${SOURCE_ROOT}/src/game/Server/WorldSession.cpp" world_session)
file(READ "${SOURCE_ROOT}/src/game/WorldHandlers/SpellEffectSkillEnchantPet.cpp" dispel_effect)
file(READ "${SOURCE_ROOT}/src/game/WorldHandlers/SpellEffectTail.cpp" steal_effect)

if(spell_packets MATCHES "SMSG_SPELLLOGEXECUTE")
    message(FATAL_ERROR "legacy execute-log opcode remains in SpellPackets.cpp")
endif()
if(unit_cpp MATCHES "SMSG_PERIODICAURALOG")
    message(FATAL_ERROR "legacy periodic-aura opcode remains in Unit.cpp")
endif()

foreach(sender IN ITEMS "${spell_packets}" "${unit_cpp}")
    if(NOT sender MATCHES "MopCombatLogPackets::Build")
        message(FATAL_ERROR "combat-log sender bypasses the shared 5.4.8 serializer")
    endif()
endforeach()

if(NOT spell_packets MATCHES "MopCombatLogPackets::BuildSpellExecuteLog")
    message(FATAL_ERROR "execute-log sender does not call the shared 18414 serializer")
endif()
if(NOT spell_packets MATCHES "SMSG_SPELL_EXECUTE_LOG")
    message(FATAL_ERROR "execute-log sender does not use the 18414 successor opcode")
endif()
if(NOT unit_cpp MATCHES "MopCombatLogPackets::BuildPeriodicAuraLog")
    message(FATAL_ERROR "periodic-aura sender does not call the shared 18414 serializer")
endif()
if(NOT unit_cpp MATCHES "SMSG_SPELL_PERIODIC_AURA_LOG")
    message(FATAL_ERROR "periodic-aura sender does not use the 18414 successor opcode")
endif()
if(NOT opcodes_cpp MATCHES "DefS\\(SMSG_SPELL_EXECUTE_LOG, \"SMSG_SPELL_EXECUTE_LOG\"\\)")
    message(FATAL_ERROR "execute-log successor lacks outbound opcode metadata")
endif()
if(NOT opcodes_cpp MATCHES "DefS\\(SMSG_SPELL_PERIODIC_AURA_LOG, \"SMSG_SPELL_PERIODIC_AURA_LOG\"\\)")
    message(FATAL_ERROR "periodic-aura successor lacks outbound opcode metadata")
endif()

foreach(sender IN ITEMS "${dispel_effect}" "${steal_effect}")
    if(NOT sender MATCHES "MopCombatLogPackets::BuildDispelLog")
        message(FATAL_ERROR "dispel/steal sender bypasses the shared 5.4.8 serializer")
    endif()
    if(NOT sender MATCHES "SMSG_SPELLDISPELLOG")
        message(FATAL_ERROR "dispel/steal sender does not use the merged 5.4.8 opcode")
    endif()
endforeach()
if(NOT dispel_effect MATCHES "log.isSteal = false" OR NOT steal_effect MATCHES "log.isSteal = true")
    message(FATAL_ERROR "dispel/steal call sites do not select distinct 5.4.8 event variants")
endif()
foreach(sender IN ITEMS "${dispel_effect}" "${steal_effect}")
    if(NOT sender MATCHES "log.isBreak = false")
        message(FATAL_ERROR "current dispel/steal path incorrectly selects an aura-break event")
    endif()
endforeach()
if(NOT dispel_effect MATCHES "RemoveAuraHolderDueToSpellByDispel" OR
   NOT dispel_effect MATCHES "SPELLCATEGORY_DEVOUR_MAGIC" OR
   NOT steal_effect MATCHES "RemoveAurasDueToSpellBySteal")
    message(FATAL_ERROR "combat-log migration removed a gameplay aura/heal side effect")
endif()
if(steal_effect MATCHES "SMSG_SPELLSTEALLOG" OR opcodes_h MATCHES "SMSG_SPELLSTEALLOG")
    message(FATAL_ERROR "obsolete standalone spell-steal opcode remains")
endif()
if(NOT opcodes_cpp MATCHES "DefS\\(SMSG_SPELLDISPELLOG, \"SMSG_SPELLDISPELLOG\"\\)")
    message(FATAL_ERROR "merged dispel/steal log lacks outbound opcode metadata")
endif()
if(NOT opcode_reference MATCHES "SMSG_SPELLDISPELLOG[ ]+0x0DF9  ACTIVE")
    message(FATAL_ERROR "reference inventory does not reflect active merged dispel/steal log")
endif()
if(NOT world_session MATCHES "case SMSG_SPELLDISPELLOG:")
    message(FATAL_ERROR "merged dispel/steal log remains blocked by enter-world suppression")
endif()
