file(READ "${SOURCE_ROOT}/src/game/Object/PlayerCombat.cpp" player_combat)
file(READ "${SOURCE_ROOT}/src/game/Object/UnitSpeed.cpp" unit_speed)
file(READ "${SOURCE_ROOT}/src/game/ChatCommands/PlayerStatsMods.cpp" player_stats_mods)
file(READ "${SOURCE_ROOT}/src/game/WorldHandlers/GroupHandler.cpp" group_handler)
file(READ "${SOURCE_ROOT}/src/game/WorldHandlers/InstanceData.cpp" instance_data)
file(READ "${SOURCE_ROOT}/src/game/Object/PlayerInstance.cpp" player_instance)
file(READ "${SOURCE_ROOT}/src/game/Server/Opcodes.cpp" opcode_registry)

if(player_combat MATCHES "WorldPacket[ \t]+data\\(SMSG_ATTACKSWING_NOTINRANGE")
    message(FATAL_ERROR "legacy construction SMSG_ATTACKSWING_NOTINRANGE remains in its sender")
endif()
if(player_combat MATCHES "WorldPacket[ \t]+data\\(SMSG_ATTACKSWING_BADFACING")
    message(FATAL_ERROR "legacy construction SMSG_ATTACKSWING_BADFACING remains in its sender")
endif()
if(player_combat MATCHES "WorldPacket[ \t]+data\\(SMSG_ATTACKSWING_DEADTARGET")
    message(FATAL_ERROR "legacy construction SMSG_ATTACKSWING_DEADTARGET remains in its sender")
endif()
if(player_combat MATCHES "WorldPacket[ \t]+data\\(SMSG_ATTACKSWING_CANT_ATTACK")
    message(FATAL_ERROR "legacy construction SMSG_ATTACKSWING_CANT_ATTACK remains in its sender")
endif()
if(player_stats_mods MATCHES "Initialize\\(SMSG_FORCE_SWIM_SPEED_CHANGE")
    message(FATAL_ERROR "legacy construction SMSG_FORCE_SWIM_SPEED_CHANGE remains in its sender")
endif()
if(group_handler MATCHES "WorldPacket[ \t]+data\\(MSG_RANDOM_ROLL")
    message(FATAL_ERROR "legacy construction MSG_RANDOM_ROLL remains in its sender")
endif()
if(instance_data MATCHES "WorldPacket[ \t]+data\\(SMSG_INSTANCE_ENCOUNTER")
    message(FATAL_ERROR "legacy construction SMSG_INSTANCE_ENCOUNTER remains in its sender")
endif()
if(player_instance MATCHES "WorldPacket[ \t]+data\\(MSG_SET_RAID_DIFFICULTY")
    message(FATAL_ERROR "legacy construction MSG_SET_RAID_DIFFICULTY remains in its sender")
endif()

foreach(source_text IN ITEMS "${unit_speed}" "${player_stats_mods}")
    if(NOT source_text MATCHES "MopCompactPackets::BuildMoveSetSwimSpeed")
        message(FATAL_ERROR "swim-speed sender bypasses the shared 5.4.8 serializer")
    endif()
endforeach()

foreach(server_name IN ITEMS
        SMSG_ATTACKSWING_ERROR
        SMSG_MOVE_SET_SWIM_SPEED
        SMSG_RANDOM_ROLL
        SMSG_UPDATE_INSTANCE_ENCOUNTER_UNIT
        SMSG_SET_RAID_DIFFICULTY)
    if(NOT opcode_registry MATCHES "DefS\\(${server_name},[ \t]*\"${server_name}\"\\)")
        message(FATAL_ERROR "${server_name} is missing outbound opcode metadata")
    endif()
endforeach()
