file(READ "${SOURCE_ROOT}/src/game/Object/Player.h" player_header)
file(READ "${SOURCE_ROOT}/src/game/WorldHandlers/PetHandler.cpp" pet_handler)
file(READ "${SOURCE_ROOT}/src/game/Server/Opcodes.cpp" opcode_registry)
file(READ "${SOURCE_ROOT}/src/game/Server/Opcodes.h" opcode_header)
file(READ "${SOURCE_ROOT}/src/game/Server/WorldSession.cpp" world_session)
file(READ "${SOURCE_ROOT}/src/game/Server/WorldSession.h" world_session_header)

if(MUTATION STREQUAL "pet_count_width")
    string(REPLACE "out.WriteBits(0, 19);" "out.WriteBits(0, 18);" player_header "${player_header}")
elseif(MUTATION STREQUAL "writable")
    string(REPLACE "out.WriteBit(true);" "out.WriteBit(false);" player_header "${player_header}")
elseif(MUTATION STREQUAL "slot_count_width")
    string(REPLACE "out.WriteBits(0, 25);" "out.WriteBits(0, 24);" player_header "${player_header}")
elseif(MUTATION STREQUAL "flush")
    string(REPLACE "out.FlushBits();" "// missing flush" player_header "${player_header}")
elseif(MUTATION STREQUAL "trap_level")
    string(REPLACE "out << uint16(0xFFFF);" "out << uint16(0);" player_header "${player_header}")
elseif(MUTATION STREQUAL "handler")
    string(REPLACE "MopBattlePetPackets::BuildEmptyJournal(data);" "// response omitted" pet_handler "${pet_handler}")
elseif(MUTATION STREQUAL "send")
    string(REPLACE "SendPacket(&data);" "// packet not sent" pet_handler "${pet_handler}")
elseif(MUTATION STREQUAL "client_registration")
    string(REPLACE "DefC(CMSG_BATTLE_PET_REQUEST_JOURNAL," "DefC(CMSG_UNUSED_BATTLE_PET_REQUEST_JOURNAL," opcode_registry "${opcode_registry}")
elseif(MUTATION STREQUAL "server_registration")
    string(REPLACE "DefS(SMSG_BATTLE_PET_JOURNAL," "DefS(SMSG_UNUSED_BATTLE_PET_JOURNAL," opcode_registry "${opcode_registry}")
elseif(MUTATION STREQUAL "whitelist")
    string(REPLACE "case SMSG_BATTLE_PET_JOURNAL:" "case SMSG_UNUSED_BATTLE_PET_JOURNAL:" world_session "${world_session}")
elseif(MUTATION STREQUAL "client_value")
    string(REPLACE "CMSG_BATTLE_PET_REQUEST_JOURNAL             = 0x0A23" "CMSG_BATTLE_PET_REQUEST_JOURNAL             = 0x0000" opcode_header "${opcode_header}")
elseif(MUTATION STREQUAL "server_value")
    string(REPLACE "SMSG_BATTLE_PET_JOURNAL                      = 0x1542" "SMSG_BATTLE_PET_JOURNAL                      = 0x0000" opcode_header "${opcode_header}")
endif()

foreach(fragment IN ITEMS
        "namespace MopBattlePetPackets"
        "out.Initialize(SMSG_BATTLE_PET_JOURNAL, 8);"
        "out.WriteBits(0, 19);"
        "out.WriteBit(true);"
        "out.WriteBits(0, 25);"
        "out.FlushBits();"
        "out << uint16(0xFFFF);")
    string(FIND "${player_header}" "${fragment}" found)
    if(found EQUAL -1)
        message(FATAL_ERROR "battle-pet journal builder is missing or its 18414 layout drifted: ${fragment}")
    endif()
endforeach()

string(FIND "${pet_handler}" "void WorldSession::HandleBattlePetRequestJournal(WorldPacket&" handler_definition)
if(handler_definition EQUAL -1)
    message(FATAL_ERROR "battle-pet journal request handler is missing")
endif()
string(FIND "${pet_handler}" "MopBattlePetPackets::BuildEmptyJournal(data);" handler_response)
if(handler_response EQUAL -1)
    message(FATAL_ERROR "battle-pet journal handler does not send the 18414 response")
endif()
string(FIND "${pet_handler}" "SendPacket(&data);" handler_send)
if(handler_send EQUAL -1)
    message(FATAL_ERROR "battle-pet journal handler does not transmit its response")
endif()
string(FIND "${world_session_header}" "void HandleBattlePetRequestJournal(WorldPacket& recv_data);" handler_declaration)
if(handler_declaration EQUAL -1)
    message(FATAL_ERROR "battle-pet journal handler declaration is missing")
endif()

set(client_registration "DefC(CMSG_BATTLE_PET_REQUEST_JOURNAL, \"CMSG_BATTLE_PET_REQUEST_JOURNAL\", STATUS_LOGGEDIN, PROCESS_THREADUNSAFE, &WorldSession::HandleBattlePetRequestJournal);")
string(FIND "${opcode_registry}" "${client_registration}" client_registration_exact)
if(client_registration_exact EQUAL -1)
    message(FATAL_ERROR "battle-pet journal request registration tuple is wrong")
endif()
string(REGEX MATCHALL "DefC\\(CMSG_BATTLE_PET_REQUEST_JOURNAL," client_registrations "${opcode_registry}")
list(LENGTH client_registrations client_registration_count)
if(NOT client_registration_count EQUAL 1)
    message(FATAL_ERROR "expected exactly one battle-pet journal request registration")
endif()

set(server_registration "DefS(SMSG_BATTLE_PET_JOURNAL, \"SMSG_BATTLE_PET_JOURNAL\");")
string(FIND "${opcode_registry}" "${server_registration}" server_registration_exact)
if(server_registration_exact EQUAL -1)
    message(FATAL_ERROR "battle-pet journal response registration tuple is wrong")
endif()
string(REGEX MATCHALL "DefS\\(SMSG_BATTLE_PET_JOURNAL," server_registrations "${opcode_registry}")
list(LENGTH server_registrations server_registration_count)
if(NOT server_registration_count EQUAL 1)
    message(FATAL_ERROR "expected exactly one battle-pet journal response registration")
endif()

string(FIND "${world_session}" "case SMSG_BATTLE_PET_JOURNAL:" whitelist)
if(whitelist EQUAL -1)
    message(FATAL_ERROR "battle-pet journal response is not admitted through send suppression")
endif()
string(FIND "${opcode_header}" "CMSG_BATTLE_PET_REQUEST_JOURNAL             = 0x0A23" client_value)
if(client_value EQUAL -1)
    message(FATAL_ERROR "battle-pet journal request opcode drifted")
endif()
string(FIND "${opcode_header}" "SMSG_BATTLE_PET_JOURNAL                      = 0x1542" server_value)
if(server_value EQUAL -1)
    message(FATAL_ERROR "battle-pet journal response opcode drifted")
endif()
