file(READ "${SOURCE_ROOT}/src/game/BattleGround/BattleGround.h" battleground_header)
file(READ "${SOURCE_ROOT}/src/game/BattleGround/BattleGround.cpp" battleground_source)
file(READ "${SOURCE_ROOT}/src/game/BattleGround/BattleGroundHandler.cpp" battleground_handler)
file(READ "${SOURCE_ROOT}/src/game/Server/Opcodes.cpp" opcode_registry)
file(READ "${SOURCE_ROOT}/src/game/Server/Opcodes.h" opcode_header)
file(READ "${SOURCE_ROOT}/src/game/Server/WorldSession.cpp" world_session)
file(READ "${SOURCE_ROOT}/src/game/Server/WorldSession.h" world_session_header)

if(MUTATION STREQUAL "builder_order")
    string(REPLACE "out << maxTime << timeRemaining << timerType;" "out << timerType << timeRemaining << maxTime;" battleground_header "${battleground_header}")
elseif(MUTATION STREQUAL "callsites")
    string(REPLACE "MopBattleGroundPackets::BuildStartTimer(data," "MopBrokenPackets::BuildStartTimer(data," battleground_source "${battleground_source}")
elseif(MUTATION STREQUAL "request_reader")
    string(REPLACE "recv_data.read_skip<uint32>();" "// timer type omitted" battleground_handler "${battleground_handler}")
elseif(MUTATION STREQUAL "client_registration")
    string(REPLACE "DefC(CMSG_QUERY_COUNTDOWN_TIMER," "DefC(CMSG_UNUSED_QUERY_COUNTDOWN_TIMER," opcode_registry "${opcode_registry}")
elseif(MUTATION STREQUAL "server_registration")
    string(REPLACE "DefS(SMSG_START_TIMER," "DefS(SMSG_UNUSED_START_TIMER," opcode_registry "${opcode_registry}")
elseif(MUTATION STREQUAL "whitelist")
    string(REPLACE "case SMSG_START_TIMER:" "case SMSG_UNUSED_START_TIMER:" world_session "${world_session}")
elseif(MUTATION STREQUAL "client_value")
    string(REPLACE "CMSG_QUERY_COUNTDOWN_TIMER                   = 0x044E" "CMSG_QUERY_COUNTDOWN_TIMER                   = 0x0000" opcode_header "${opcode_header}")
elseif(MUTATION STREQUAL "server_value")
    string(REPLACE "SMSG_START_TIMER                             = 0x0E3F" "SMSG_START_TIMER                             = 0x0000" opcode_header "${opcode_header}")
endif()

string(FIND "${battleground_header}" "namespace MopBattleGroundPackets" builder_declaration)
if(builder_declaration EQUAL -1)
    message(FATAL_ERROR "battleground timer builder is not declared in owning gameplay code")
endif()
string(FIND "${battleground_header}" "out << maxTime << timeRemaining << timerType;" builder_order)
if(builder_order EQUAL -1)
    message(FATAL_ERROR "SMSG_START_TIMER does not use the binary-proven 18414 field order")
endif()
string(REGEX MATCHALL "MopBattleGroundPackets::BuildStartTimer\\(data," timer_calls "${battleground_source}")
list(LENGTH timer_calls timer_call_count)
if(NOT timer_call_count EQUAL 2)
    message(FATAL_ERROR "expected both active battleground countdown senders to use the 18414 builder")
endif()
string(FIND "${battleground_source}" "WorldPacket data(SMSG_START_TIMER" legacy_sender)
if(NOT legacy_sender EQUAL -1)
    message(FATAL_ERROR "legacy SMSG_START_TIMER sender remains")
endif()
string(FIND "${battleground_handler}" "void WorldSession::HandleQueryCountdownTimerOpcode(WorldPacket& recv_data)" request_handler)
if(request_handler EQUAL -1)
    message(FATAL_ERROR "CMSG_QUERY_COUNTDOWN_TIMER handler is missing")
endif()
string(FIND "${battleground_handler}" "recv_data.read_skip<uint32>();" request_reader)
if(request_reader EQUAL -1)
    message(FATAL_ERROR "CMSG_QUERY_COUNTDOWN_TIMER does not consume its uint32 timer type")
endif()
string(FIND "${world_session_header}" "void HandleQueryCountdownTimerOpcode(WorldPacket& recv_data);" handler_declaration)
if(handler_declaration EQUAL -1)
    message(FATAL_ERROR "CMSG_QUERY_COUNTDOWN_TIMER handler declaration is missing")
endif()
string(FIND "${opcode_registry}" "DefC(CMSG_QUERY_COUNTDOWN_TIMER, \"CMSG_QUERY_COUNTDOWN_TIMER\"" client_registration)
if(client_registration EQUAL -1)
    message(FATAL_ERROR "CMSG_QUERY_COUNTDOWN_TIMER is not registered")
endif()
string(FIND "${opcode_registry}" "DefS(SMSG_START_TIMER, \"SMSG_START_TIMER\")" server_registration)
if(server_registration EQUAL -1)
    message(FATAL_ERROR "SMSG_START_TIMER is missing outbound metadata")
endif()
string(FIND "${world_session}" "case SMSG_START_TIMER:" whitelist)
if(whitelist EQUAL -1)
    message(FATAL_ERROR "SMSG_START_TIMER is not admitted through send suppression")
endif()
string(FIND "${opcode_header}" "CMSG_QUERY_COUNTDOWN_TIMER                   = 0x044E" client_value)
if(client_value EQUAL -1)
    message(FATAL_ERROR "CMSG_QUERY_COUNTDOWN_TIMER value drifted")
endif()
string(FIND "${opcode_header}" "SMSG_START_TIMER                             = 0x0E3F" server_value)
if(server_value EQUAL -1)
    message(FATAL_ERROR "SMSG_START_TIMER value drifted")
endif()
