file(READ "${SOURCE_ROOT}/src/game/WorldHandlers/NPCHandler.cpp" npc_handler)
file(READ "${SOURCE_ROOT}/src/game/WorldHandlers/GossipDef.cpp" gossip_def)
file(READ "${SOURCE_ROOT}/src/game/WorldHandlers/GossipDef.h" gossip_def_header)
file(READ "${SOURCE_ROOT}/src/game/Server/Opcodes.cpp" opcode_registry)
file(READ "${SOURCE_ROOT}/src/game/Server/Opcodes.h" opcode_header)
file(READ "${SOURCE_ROOT}/src/game/Server/WorldSession.cpp" world_session)

if(MUTATION STREQUAL "request_reader")
    string(REPLACE "MopGossipPackets::ReadHello(recv_data)" "ObjectGuid()" npc_handler "${npc_handler}")
elseif(MUTATION STREQUAL "response_builder")
    string(REPLACE "MopGossipPackets::BuildMessage(data, message)" "data.Initialize(SMSG_GOSSIP_MESSAGE)" gossip_def "${gossip_def}")
elseif(MUTATION STREQUAL "select_reader")
    string(REPLACE "MopGossipPackets::ParseSelectOption(recv_data, request)" "false" npc_handler "${npc_handler}")
elseif(MUTATION STREQUAL "select_validation")
    string(REPLACE "CanSelectGossipOption(" "CanSelectUncheckedGossipOption(" npc_handler "${npc_handler}")
elseif(MUTATION STREQUAL "source_binding")
    string(REPLACE "mGossipSourceGuid = objectGuid;" "mGossipSourceGuid.Clear();" gossip_def "${gossip_def}")
elseif(MUTATION STREQUAL "source_clear")
    string(REPLACE "mGossipSourceGuid.Clear();" "/* source retained */" gossip_def "${gossip_def}")
elseif(MUTATION STREQUAL "poi_builder")
    string(REPLACE "MopGossipPackets::BuildPointOfInterest(data, point)" "false" gossip_def "${gossip_def}")
elseif(MUTATION STREQUAL "client_registration")
    string(REPLACE "DefC(CMSG_GOSSIP_HELLO," "DefC(CMSG_UNUSED_GOSSIP_HELLO," opcode_registry "${opcode_registry}")
elseif(MUTATION STREQUAL "server_registration")
    string(REPLACE "DefS(SMSG_GOSSIP_MESSAGE," "DefS(SMSG_UNUSED_GOSSIP_MESSAGE," opcode_registry "${opcode_registry}")
elseif(MUTATION STREQUAL "select_registration")
    string(REPLACE "DefC(CMSG_GOSSIP_SELECT_OPTION," "DefC(CMSG_UNUSED_GOSSIP_SELECT_OPTION," opcode_registry "${opcode_registry}")
elseif(MUTATION STREQUAL "poi_registration")
    string(REPLACE "DefS(SMSG_GOSSIP_POI," "DefS(SMSG_UNUSED_GOSSIP_POI," opcode_registry "${opcode_registry}")
elseif(MUTATION STREQUAL "whitelist")
    string(REPLACE "case SMSG_GOSSIP_MESSAGE:" "case SMSG_UNUSED_GOSSIP_MESSAGE:" world_session "${world_session}")
elseif(MUTATION STREQUAL "poi_whitelist")
    string(REPLACE "case SMSG_GOSSIP_POI:" "case SMSG_UNUSED_GOSSIP_POI:" world_session "${world_session}")
elseif(MUTATION STREQUAL "select_opcode")
    string(REPLACE "CMSG_GOSSIP_SELECT_OPTION                    = 0x0748" "CMSG_GOSSIP_SELECT_OPTION                    = 0x0000" opcode_header "${opcode_header}")
elseif(MUTATION STREQUAL "poi_opcode")
    string(REPLACE "SMSG_GOSSIP_POI                              = 0x0785" "SMSG_GOSSIP_POI                              = 0x0000" opcode_header "${opcode_header}")
endif()

string(FIND "${npc_handler}" "MopGossipPackets::ReadHello(recv_data)" request_reader)
if(request_reader EQUAL -1)
    message(FATAL_ERROR "gossip hello handler bypasses the 18414 request reader")
endif()
string(FIND "${gossip_def}" "MopGossipPackets::BuildMessage(data, message)" response_builder)
if(response_builder EQUAL -1)
    message(FATAL_ERROR "gossip menu sender bypasses the 18414 response builder")
endif()
string(FIND "${npc_handler}" "MopGossipPackets::ParseSelectOption(recv_data, request)" select_reader)
if(select_reader EQUAL -1)
    message(FATAL_ERROR "gossip option handler bypasses the 18414 request reader")
endif()
string(FIND "${npc_handler}" "CanSelectGossipOption(" select_validation)
string(FIND "${npc_handler}" "GossipOptionSender(" select_sender)
if(select_validation EQUAL -1 OR
        (NOT select_sender EQUAL -1 AND select_validation GREATER select_sender))
    message(FATAL_ERROR "gossip option state is exposed before request validation")
endif()
string(FIND "${gossip_def}" "mGossipSourceGuid = objectGuid;" source_binding)
if(source_binding EQUAL -1)
    message(FATAL_ERROR "sent gossip menu is not bound to its source GUID")
endif()
string(REGEX MATCHALL "mGossipSourceGuid\\.Clear\\(\\);" source_clears "${gossip_def}")
list(LENGTH source_clears source_clear_count)
if(source_clear_count LESS 2)
    message(FATAL_ERROR "gossip source binding is not cleared with menu closure/lifecycle")
endif()
string(REGEX MATCHALL "MopGossipPackets::BuildPointOfInterest\\(data, point\\)" poi_builders "${gossip_def}")
list(LENGTH poi_builders poi_builder_count)
if(NOT poi_builder_count EQUAL 2)
    message(FATAL_ERROR "core gossip POI senders bypass the proved 18414 builder")
endif()
string(FIND "${gossip_def_header}" "point.name.size() > 63" poi_name_limit)
if(poi_name_limit EQUAL -1)
    message(FATAL_ERROR "gossip POI builder does not enforce the client text buffer")
endif()
string(FIND "${gossip_def}" "data << ObjectGuid(objectGuid)" legacy_guid)
if(NOT legacy_guid EQUAL -1)
    message(FATAL_ERROR "legacy flat gossip GUID serialization remains")
endif()
string(FIND "${gossip_def}" "WorldPacket data(SMSG_GOSSIP_POI" legacy_poi)
if(NOT legacy_poi EQUAL -1)
    message(FATAL_ERROR "legacy direct gossip POI serialization remains")
endif()
string(FIND "${opcode_registry}" "DefC(CMSG_GOSSIP_HELLO, \"CMSG_GOSSIP_HELLO\"" client_registration)
if(client_registration EQUAL -1)
    message(FATAL_ERROR "CMSG_GOSSIP_HELLO is not registered")
endif()
string(FIND "${opcode_registry}" "DefS(SMSG_GOSSIP_MESSAGE, \"SMSG_GOSSIP_MESSAGE\")" server_registration)
if(server_registration EQUAL -1)
    message(FATAL_ERROR "SMSG_GOSSIP_MESSAGE is missing outbound metadata")
endif()
string(FIND "${opcode_registry}" "DefC(CMSG_GOSSIP_SELECT_OPTION, \"CMSG_GOSSIP_SELECT_OPTION\"" select_registration)
if(select_registration EQUAL -1)
    message(FATAL_ERROR "CMSG_GOSSIP_SELECT_OPTION is not registered")
endif()
string(FIND "${opcode_registry}" "DefS(SMSG_GOSSIP_POI, \"SMSG_GOSSIP_POI\")" poi_registration)
if(poi_registration EQUAL -1)
    message(FATAL_ERROR "SMSG_GOSSIP_POI is missing outbound metadata")
endif()
string(FIND "${world_session}" "case SMSG_GOSSIP_MESSAGE:" whitelist)
if(whitelist EQUAL -1)
    message(FATAL_ERROR "SMSG_GOSSIP_MESSAGE is not admitted through send suppression")
endif()
string(FIND "${world_session}" "case SMSG_GOSSIP_POI:" poi_whitelist)
if(poi_whitelist EQUAL -1)
    message(FATAL_ERROR "SMSG_GOSSIP_POI is not admitted through send suppression")
endif()
string(FIND "${opcode_header}" "CMSG_GOSSIP_HELLO                            = 0x12F3" client_value)
if(client_value EQUAL -1)
    message(FATAL_ERROR "CMSG_GOSSIP_HELLO value drifted")
endif()
string(FIND "${opcode_header}" "SMSG_GOSSIP_MESSAGE                          = 0x0244" server_value)
if(server_value EQUAL -1)
    message(FATAL_ERROR "SMSG_GOSSIP_MESSAGE value drifted")
endif()
string(FIND "${opcode_header}" "CMSG_GOSSIP_SELECT_OPTION                    = 0x0748" select_value)
if(select_value EQUAL -1)
    message(FATAL_ERROR "CMSG_GOSSIP_SELECT_OPTION value drifted")
endif()
string(FIND "${opcode_header}" "SMSG_GOSSIP_POI                              = 0x0785" poi_value)
if(poi_value EQUAL -1)
    message(FATAL_ERROR "SMSG_GOSSIP_POI value drifted")
endif()
