file(READ "${SOURCE_ROOT}/src/game/Object/Player.cpp" player_source)
file(READ "${SOURCE_ROOT}/src/game/Object/PlayerQuest.cpp" quest_source)
file(READ "${SOURCE_ROOT}/src/game/Object/PlayerLoad.cpp" player_load)
file(READ "${SOURCE_ROOT}/src/game/Object/PlayerSave.cpp" player_save)
file(READ "${SOURCE_ROOT}/src/game/ChatCommands/QuestCommands.cpp" quest_commands)
file(READ "${SOURCE_ROOT}/src/game/WorldHandlers/SpellEffectDamageTeleport.cpp" spell_effects)
file(READ "${SOURCE_ROOT}/src/game/Server/DBCStores.cpp" dbc_stores)
file(READ "${SOURCE_ROOT}/src/game/Server/WorldSession.cpp" session_source)

function(require_contains source token context)
    string(FIND "${source}" "${token}" position)
    if(position EQUAL -1)
        message(FATAL_ERROR "${context}: required token not found: ${token}")
    endif()
endfunction()

require_contains("${dbc_stores}" "sQuestV2Store" "QuestV2 DBC store")
require_contains("${dbc_stores}" "QuestV2.dbc" "QuestV2 DBC load")
require_contains("${player_source}" "SendInitialQuestSetup();" "login snapshot send")
require_contains("${quest_source}" "MopQuestPackets::BuildInitialSetup" "initial snapshot builder call")
require_contains("${quest_source}" "SendQuestCompletedBit(quest_id);" "reward set-bit delta")
require_contains("${quest_source}" "SendClearQuestCompletedBits(m_dailyquests);" "daily clear-many delta")
require_contains("${quest_source}" "SendClearQuestCompletedBits(m_weeklyquests);" "weekly clear-many delta")
require_contains("${quest_source}" "SendClearQuestCompletedBits(m_monthlyquests);" "monthly clear-many delta")
require_contains("${player_load}" "m_dailyquests.insert(quest_id);" "daily quest load tracking")
require_contains("${player_save}" "for (QuestSet::const_iterator iter = m_dailyquests.begin()" "daily quest save tracking")
require_contains("${quest_commands}" "ClearQuestRewardStatus(entry);" "command clear delta")
require_contains("${spell_effects}" "ClearQuestRewardStatus(quest_id);" "spell clear delta")

foreach(opcode IN ITEMS SMSG_INITIAL_SETUP SMSG_SET_QUEST_COMPLETED_BIT
        SMSG_CLEAR_QUEST_COMPLETED_BIT SMSG_CLEAR_QUEST_COMPLETED_BITS)
    require_contains("${session_source}" "case ${opcode}:" "${opcode} suppression whitelist")
endforeach()
