file(READ "${SOURCE_ROOT}/src/game/WorldHandlers/SpellPackets.cpp" spell_packets)
file(READ "${SOURCE_ROOT}/src/game/Object/Unit.cpp" unit_cpp)
file(READ "${SOURCE_ROOT}/src/game/Server/Opcodes.cpp" opcodes_cpp)

if(spell_packets MATCHES "SMSG_SPELLLOGEXECUTE")
    message(FATAL_ERROR "legacy execute-log opcode remains in SpellPackets.cpp")
endif()
if(unit_cpp MATCHES "SMSG_PERIODICAURALOG")
    message(FATAL_ERROR "legacy periodic-aura opcode remains in Unit.cpp")
endif()

foreach(sender IN ITEMS "${spell_packets}" "${unit_cpp}")
    if(NOT sender MATCHES "MopCombatLogPackets::Build")
        message(FATAL_ERROR "combat-log sender bypasses the shared 5.4.8 serializer")
    endif()
endforeach()

if(NOT spell_packets MATCHES "MopCombatLogPackets::BuildSpellExecuteLog")
    message(FATAL_ERROR "execute-log sender does not call the shared 18414 serializer")
endif()
if(NOT spell_packets MATCHES "SMSG_SPELL_EXECUTE_LOG")
    message(FATAL_ERROR "execute-log sender does not use the 18414 successor opcode")
endif()
if(NOT unit_cpp MATCHES "MopCombatLogPackets::BuildPeriodicAuraLog")
    message(FATAL_ERROR "periodic-aura sender does not call the shared 18414 serializer")
endif()
if(NOT unit_cpp MATCHES "SMSG_SPELL_PERIODIC_AURA_LOG")
    message(FATAL_ERROR "periodic-aura sender does not use the 18414 successor opcode")
endif()
if(NOT opcodes_cpp MATCHES "DefS\\(SMSG_SPELL_EXECUTE_LOG, \"SMSG_SPELL_EXECUTE_LOG\"\\)")
    message(FATAL_ERROR "execute-log successor lacks outbound opcode metadata")
endif()
if(NOT opcodes_cpp MATCHES "DefS\\(SMSG_SPELL_PERIODIC_AURA_LOG, \"SMSG_SPELL_PERIODIC_AURA_LOG\"\\)")
    message(FATAL_ERROR "periodic-aura successor lacks outbound opcode metadata")
endif()
