file(READ "${SOURCE_ROOT}/src/game/Server/Opcodes.cpp" opcodes)
file(READ "${SOURCE_ROOT}/src/game/Server/Opcodes.h" opcode_header)
file(READ "${SOURCE_ROOT}/src/game/WorldHandlers/MiscHandler.cpp" misc)
file(READ "${SOURCE_ROOT}/src/game/WorldHandlers/CombatHandler.cpp" combat)
file(READ "${SOURCE_ROOT}/src/game/WorldHandlers/ChannelHandler.cpp" channel)
file(READ "${SOURCE_ROOT}/src/game/WorldHandlers/CharacterHandlerCustomize.cpp" character)
file(READ "${SOURCE_ROOT}/src/game/WorldHandlers/ItemHandler.cpp" item)
file(READ "${SOURCE_ROOT}/src/game/WorldHandlers/MovementHandler.cpp" movement)
file(READ "${SOURCE_ROOT}/src/game/WorldHandlers/VoiceChatHandler.cpp" voice)
file(READ "${SOURCE_ROOT}/src/game/Server/WorldSession.cpp" session)
file(READ "${SOURCE_ROOT}/src/game/Object/Player.h" player_header)
file(READ "${SOURCE_ROOT}/src/game/Object/PlayerLoad.cpp" player_load)
file(READ "${SOURCE_ROOT}/src/game/WorldHandlers/GroupHandler.cpp" group)
file(READ "${SOURCE_ROOT}/src/game/Object/Unit.cpp" unit)
file(READ "${SOURCE_ROOT}/src/game/Object/UnitCombat.cpp" unit_combat)
file(READ "${SOURCE_ROOT}/src/game/Object/Unit.h" unit_header)
file(READ "${SOURCE_ROOT}/src/game/WorldHandlers/QuestHandler.cpp" quest)
file(READ "${SOURCE_ROOT}/src/game/WorldHandlers/GossipDef.cpp" gossip)
file(READ "${SOURCE_ROOT}/src/game/BattleGround/BattleGroundHandler.cpp" battleground)

if(MUTATION STREQUAL "logout_manual_registration")
    string(REPLACE "DefC(CMSG_LOGOUT_REQUEST," "DefC(CMSG_UNUSED_LOGOUT_REQUEST," opcodes "${opcodes}")
elseif(MUTATION STREQUAL "logout_idle_registration")
    string(REPLACE "DefC(CMSG_LOGOUT_REQUEST_IDLE," "DefC(CMSG_UNUSED_LOGOUT_REQUEST_IDLE," opcodes "${opcodes}")
elseif(MUTATION STREQUAL "logout_manual_value")
    string(REPLACE "CMSG_LOGOUT_REQUEST                          = 0x0643" "CMSG_LOGOUT_REQUEST                          = 0x0000" opcode_header "${opcode_header}")
elseif(MUTATION STREQUAL "violence_registration")
    string(REPLACE "DefC(CMSG_VIOLENCE_LEVEL," "DefC(CMSG_UNUSED_VIOLENCE_LEVEL," opcodes "${opcodes}")
elseif(MUTATION STREQUAL "violence_handler")
    string(REPLACE "recv_data.read_skip<uint8>();" "recv_data.rfinish();" misc "${misc}")
elseif(MUTATION STREQUAL "violence_value")
    string(REPLACE "CMSG_VIOLENCE_LEVEL                         = 0x0040" "CMSG_VIOLENCE_LEVEL                         = 0x0000" opcode_header "${opcode_header}")
elseif(MUTATION STREQUAL "battlefield_status_registration")
    string(REPLACE "DefC(CMSG_BATTLEFIELD_STATUS," "DefC(CMSG_UNUSED_BATTLEFIELD_STATUS," opcodes "${opcodes}")
elseif(MUTATION STREQUAL "battle_pay_registration")
    string(REPLACE "DefC(CMSG_BATTLE_PAY_GET_PURCHASE_LIST," "DefC(CMSG_UNUSED_BATTLE_PAY_GET_PURCHASE_LIST," opcodes "${opcodes}")
elseif(MUTATION STREQUAL "battle_pay_duplicate_raw")
    string(REPLACE
        "DefC(CMSG_BATTLE_PAY_GET_PURCHASE_LIST, \"CMSG_BATTLE_PAY_GET_PURCHASE_LIST\", STATUS_AUTHED, PROCESS_INPLACE, &WorldSession::Handle_NULL);"
        "DefC(CMSG_BATTLE_PAY_GET_PURCHASE_LIST, \"CMSG_BATTLE_PAY_GET_PURCHASE_LIST\", STATUS_AUTHED, PROCESS_INPLACE, &WorldSession::Handle_NULL);\n    DefC(0x18B2, \"CMSG_BATTLE_PAY_GET_PURCHASE_LIST\", STATUS_AUTHED, PROCESS_INPLACE, &WorldSession::Handle_NULL);"
        opcodes "${opcodes}")
elseif(MUTATION STREQUAL "battle_pay_value")
    string(REPLACE "CMSG_BATTLE_PAY_GET_PURCHASE_LIST            = 0x18B2" "CMSG_BATTLE_PAY_GET_PURCHASE_LIST            = 0x0000" opcode_header "${opcode_header}")
elseif(MUTATION STREQUAL "missile_cancel_reintroduced")
    string(REPLACE
        "SMSG_PET_BATTLE_QUEUE_PROPOSE_MATCH          = 0x1202,"
        "SMSG_PET_BATTLE_QUEUE_PROPOSE_MATCH          = 0x1202,\n    SMSG_MISSILE_CANCEL                          = 0x1203,"
        opcode_header "${opcode_header}")
endif()

string(FIND "${opcode_header}" "CMSG_LOGOUT_REQUEST                          = 0x0643" logout_manual_value)
if(logout_manual_value EQUAL -1)
    message(FATAL_ERROR "CMSG_LOGOUT_REQUEST must be the manual 0x0643 route")
endif()
string(FIND "${opcode_header}" "CMSG_LOGOUT_REQUEST_IDLE                     = 0x1349" logout_idle_value)
if(logout_idle_value EQUAL -1)
    message(FATAL_ERROR "CMSG_LOGOUT_REQUEST_IDLE must be the automatic-idle 0x1349 route")
endif()

foreach(route IN ITEMS CMSG_LOGOUT_REQUEST CMSG_LOGOUT_REQUEST_IDLE)
    set(expected_registration
        "DefC(${route}, \"${route}\", STATUS_LOGGEDIN, PROCESS_THREADUNSAFE, &WorldSession::HandleLogoutRequestOpcode);")
    string(FIND "${opcodes}" "${expected_registration}" exact_registration)
    string(REGEX MATCHALL "DefC\\(${route}," registrations "${opcodes}")
    list(LENGTH registrations registration_count)
    if(exact_registration EQUAL -1 OR NOT registration_count EQUAL 1)
        message(FATAL_ERROR "${route} must be registered exactly once to HandleLogoutRequestOpcode as STATUS_LOGGEDIN/PROCESS_THREADUNSAFE")
    endif()
endforeach()

set(expected_logout_cancel_registration
    "DefC(CMSG_LOGOUT_CANCEL, \"CMSG_LOGOUT_CANCEL\", STATUS_LOGGEDIN, PROCESS_THREADUNSAFE, &WorldSession::HandleLogoutCancelOpcode);")
string(FIND "${opcodes}" "${expected_logout_cancel_registration}" exact_logout_cancel_registration)
string(REGEX MATCHALL "DefC\\(CMSG_LOGOUT_CANCEL," logout_cancel_registrations "${opcodes}")
list(LENGTH logout_cancel_registrations logout_cancel_registration_count)
if(exact_logout_cancel_registration EQUAL -1 OR NOT logout_cancel_registration_count EQUAL 1)
    message(FATAL_ERROR "CMSG_LOGOUT_CANCEL registration changed")
endif()

foreach(response IN ITEMS SMSG_LOGOUT_RESPONSE SMSG_LOGOUT_CANCEL_ACK SMSG_LOGOUT_COMPLETE)
    set(expected_response_registration "DefS(${response}, \"${response}\");")
    string(FIND "${opcodes}" "${expected_response_registration}" exact_response_registration)
    string(REGEX MATCHALL "DefS\\(${response}," response_registrations "${opcodes}")
    list(LENGTH response_registrations response_registration_count)
    if(exact_response_registration EQUAL -1 OR NOT response_registration_count EQUAL 1)
        message(FATAL_ERROR "${response} registration changed")
    endif()
    string(REGEX MATCHALL "case[ \t]+${response}:" response_admissions "${session}")
    list(LENGTH response_admissions response_admission_count)
    if(NOT response_admission_count EQUAL 1)
        message(FATAL_ERROR "${response} suppression admission changed")
    endif()
endforeach()

string(FIND "${misc}" "void WorldSession::HandleLogoutRequestOpcode" logout_handler_start)
string(FIND "${misc}" "void WorldSession::HandlePlayerLogoutOpcode" logout_handler_end)
if(logout_handler_start EQUAL -1 OR logout_handler_end LESS_EQUAL logout_handler_start)
    message(FATAL_ERROR "logout-request handler body is missing")
endif()
math(EXPR logout_handler_length "${logout_handler_end} - ${logout_handler_start}")
string(SUBSTRING "${misc}" ${logout_handler_start} ${logout_handler_length} logout_handler_body)
if(logout_handler_body MATCHES "recv_data[ \t]*(>>|\\.|->)")
    message(FATAL_ERROR "empty logout-request routes must not read request data")
endif()

foreach(route IN ITEMS
        "CMSG_REQUEST_HOTFIX;HandleRequestHotfix"
        "CMSG_JOIN_CHANNEL;HandleJoinChannelOpcode"
        "CMSG_CANCEL_TRADE;HandleCancelTradeOpcode"
        "CMSG_UI_TIME_REQUEST;HandleUITimeRequestOpcode"
        "CMSG_LOAD_SCREEN;HandleLoadScreenOpcode")
    list(GET route 0 opcode)
    list(GET route 1 handler)
    if(NOT opcodes MATCHES "DefC\\(${opcode},[^\n]*&WorldSession::${handler}\\)")
        message(FATAL_ERROR "${opcode} is not registered to ${handler}")
    endif()
endforeach()

if(NOT opcodes MATCHES "DefC\\(CMSG_REQUEST_RAID_INFO,[^\n]*&WorldSession::HandleRequestRaidInfoOpcode\\)")
    message(FATAL_ERROR "CMSG_REQUEST_RAID_INFO is not registered to its handler")
endif()
if(NOT opcodes MATCHES "DefS\\(SMSG_RAID_INSTANCE_INFO,")
    message(FATAL_ERROR "SMSG_RAID_INSTANCE_INFO is not registered")
endif()
foreach(token IN ITEMS
        "namespace MopRaidInstancePackets"
        "BuildRaidInstanceInfo")
    string(FIND "${player_header}" "${token}" found)
    if(found EQUAL -1)
        message(FATAL_ERROR "raid-instance builder missing: ${token}")
    endif()
endforeach()
string(FIND "${player_load}" "MopRaidInstancePackets::BuildRaidInstanceInfo(data, records)" raid_builder)
if(raid_builder EQUAL -1)
    message(FATAL_ERROR "Player::SendRaidInfo does not use the 18414 builder")
endif()
string(FIND "${group}" "_player->SendRaidInfo();" raid_handler)
if(raid_handler EQUAL -1)
    message(FATAL_ERROR "raid-info request handler is disconnected")
endif()
string(FIND "${session}" "case SMSG_RAID_INSTANCE_INFO:" raid_gate)
if(raid_gate EQUAL -1)
    message(FATAL_ERROR "raid-instance response is not admitted through suppression")
endif()

foreach(route IN ITEMS
        "CMSG_MOVE_TIME_SKIPPED;HandleMoveTimeSkippedOpcode"
        "CMSG_SET_ACTIVE_MOVER;HandleSetActiveMoverOpcode")
    list(GET route 0 opcode)
    list(GET route 1 handler)
    if(NOT opcodes MATCHES "DefC\\(${opcode},[^\n]*&WorldSession::${handler}\\)")
        message(FATAL_ERROR "${opcode} is not registered to ${handler}")
    endif()
endforeach()

foreach(route IN ITEMS
        "CMSG_SET_ACTIONBAR_TOGGLES;HandleSetActionBarTogglesOpcode"
        "CMSG_VIOLENCE_LEVEL;HandleViolenceLevelOpcode"
        "CMSG_VOICE_SESSION_ENABLE;HandleVoiceSessionEnableOpcode")
    list(GET route 0 opcode)
    list(GET route 1 handler)
    if(NOT opcodes MATCHES "DefC\\(${opcode},[^\n]*&WorldSession::${handler}\\)")
        message(FATAL_ERROR "${opcode} is not registered to ${handler}")
    endif()
endforeach()

string(FIND "${misc}" "void WorldSession::HandleViolenceLevelOpcode" violence_start)
string(FIND "${misc}" "void WorldSession::HandlePlayedTime" violence_end)
if(violence_start EQUAL -1 OR violence_end LESS_EQUAL violence_start)
    message(FATAL_ERROR "violence-level handler body is missing")
endif()
math(EXPR violence_length "${violence_end} - ${violence_start}")
string(SUBSTRING "${misc}" ${violence_start} ${violence_length} violence_body)
string(FIND "${violence_body}" "recv_data.read_skip<uint8>();" violence_reader)
if(violence_reader EQUAL -1)
    message(FATAL_ERROR "violence-level handler does not consume the binary-proven uint8 body")
endif()
string(FIND "${opcode_header}" "CMSG_VIOLENCE_LEVEL                         = 0x0040" violence_value)
if(violence_value EQUAL -1)
    message(FATAL_ERROR "CMSG_VIOLENCE_LEVEL value drifted")
endif()

foreach(route IN ITEMS
        "CMSG_SETSHEATHED;HandleSetSheathedOpcode"
        "CMSG_SET_SELECTION;HandleSetSelectionOpcode"
        "CMSG_STANDSTATECHANGE;HandleStandStateChangeOpcode"
        "CMSG_ATTACKSWING;HandleAttackSwingOpcode"
        "CMSG_ATTACKSTOP;HandleAttackStopOpcode")
    list(GET route 0 opcode)
    list(GET route 1 handler)
    if(NOT opcodes MATCHES "DefC\\(${opcode},[^\n]*&WorldSession::${handler}\\)")
        message(FATAL_ERROR "${opcode} is not registered to ${handler}")
    endif()
endforeach()
if(NOT opcodes MATCHES "DefS\\(SMSG_STANDSTATE_UPDATE,")
    message(FATAL_ERROR "SMSG_STANDSTATE_UPDATE is not registered")
endif()

foreach(response IN ITEMS SMSG_ATTACKSTART SMSG_ATTACKSTOP)
    if(NOT opcodes MATCHES "DefS\\(${response},")
        message(FATAL_ERROR "${response} is not registered")
    endif()
    if(NOT session MATCHES "case ${response}:")
        message(FATAL_ERROR "${response} is not admitted through world-send suppression")
    endif()
endforeach()
foreach(token IN ITEMS
        "MopCompactPackets::ReadAttackSwingTarget(recv_data)"
        "MopCompactPackets::BuildAttackStop(data,")
    string(FIND "${combat}" "${token}" found)
    if(found EQUAL -1)
        message(FATAL_ERROR "combat-handler 18414 attack wiring missing: ${token}")
    endif()
endforeach()
foreach(token IN ITEMS
        "MopCompactPackets::BuildAttackStart(data,"
        "MopCompactPackets::BuildAttackStop(data,")
    string(FIND "${unit_combat}" "${token}" found)
    if(found EQUAL -1)
        message(FATAL_ERROR "unit-combat 18414 attack wiring missing: ${token}")
    endif()
endforeach()
foreach(token IN ITEMS
        "ReadAttackSwingTarget"
        "BuildAttackStart"
        "BuildAttackStop")
    string(FIND "${unit_header}" "${token}" found)
    if(found EQUAL -1)
        message(FATAL_ERROR "18414 attack codec missing: ${token}")
    endif()
endforeach()

if(NOT opcodes MATCHES "DefC\\(CMSG_QUESTGIVER_STATUS_QUERY,[^\n]*&WorldSession::HandleQuestgiverStatusQueryOpcode\\)")
    message(FATAL_ERROR "CMSG_QUESTGIVER_STATUS_QUERY is not registered to its handler")
endif()
if(NOT opcodes MATCHES "DefS\\(SMSG_QUESTGIVER_STATUS,")
    message(FATAL_ERROR "SMSG_QUESTGIVER_STATUS is not registered")
endif()
string(FIND "${session}" "case SMSG_QUESTGIVER_STATUS:" quest_status_gate)
if(quest_status_gate EQUAL -1)
    message(FATAL_ERROR "SMSG_QUESTGIVER_STATUS is not admitted through world-send suppression")
endif()
string(FIND "${quest}" "MopQuestStatusPackets::ReadStatusQuery(recv_data)" quest_status_reader)
if(quest_status_reader EQUAL -1)
    message(FATAL_ERROR "questgiver-status handler does not use the 18414 reader")
endif()
string(FIND "${gossip}" "MopQuestStatusPackets::BuildStatus(data, questStatus, npcGUID)" quest_status_writer)
if(quest_status_writer EQUAL -1)
    message(FATAL_ERROR "questgiver-status sender does not use the 18414 writer")
endif()
string(FIND "${session}" "case SMSG_STANDSTATE_UPDATE:" stand_response_gate)
if(stand_response_gate EQUAL -1)
    message(FATAL_ERROR "SMSG_STANDSTATE_UPDATE is not admitted through world-send suppression")
endif()

set(expected_battlefield_status_registration
    "DefC(CMSG_BATTLEFIELD_STATUS, \"CMSG_BATTLEFIELD_STATUS\", STATUS_LOGGEDIN, PROCESS_THREADUNSAFE, &WorldSession::HandleBattlefieldStatusOpcode);")
string(FIND "${opcodes}" "${expected_battlefield_status_registration}" exact_battlefield_status_registration)
string(REGEX MATCHALL "DefC\\(CMSG_BATTLEFIELD_STATUS," battlefield_status_registrations "${opcodes}")
list(LENGTH battlefield_status_registrations battlefield_status_registration_count)
if(exact_battlefield_status_registration EQUAL -1 OR NOT battlefield_status_registration_count EQUAL 1)
    message(FATAL_ERROR "CMSG_BATTLEFIELD_STATUS must be registered exactly once to HandleBattlefieldStatusOpcode as STATUS_LOGGEDIN/PROCESS_THREADUNSAFE")
endif()

string(FIND "${battleground}" "void WorldSession::HandleBattlefieldStatusOpcode" battlefield_status_handler_start)
string(FIND "${battleground}" "void WorldSession::HandleQueryCountdownTimerOpcode" battlefield_status_handler_end)
if(battlefield_status_handler_start EQUAL -1 OR battlefield_status_handler_end LESS_EQUAL battlefield_status_handler_start)
    message(FATAL_ERROR "battlefield-status handler body is missing")
endif()
math(EXPR battlefield_status_handler_length "${battlefield_status_handler_end} - ${battlefield_status_handler_start}")
string(SUBSTRING "${battleground}" ${battlefield_status_handler_start} ${battlefield_status_handler_length} battlefield_status_handler_body)
if(battlefield_status_handler_body MATCHES "recv_data[ \t]*(>>|\\.|->)")
    message(FATAL_ERROR "empty battlefield-status request must not read request data")
endif()

set(expected_battle_pay_registration
    "DefC(CMSG_BATTLE_PAY_GET_PURCHASE_LIST, \"CMSG_BATTLE_PAY_GET_PURCHASE_LIST\", STATUS_AUTHED, PROCESS_INPLACE, &WorldSession::Handle_NULL);")
string(FIND "${opcodes}" "${expected_battle_pay_registration}" exact_battle_pay_registration)
string(REGEX MATCHALL "DefC\\(CMSG_BATTLE_PAY_GET_PURCHASE_LIST," battle_pay_registrations "${opcodes}")
list(LENGTH battle_pay_registrations battle_pay_registration_count)
if(exact_battle_pay_registration EQUAL -1 OR NOT battle_pay_registration_count EQUAL 1)
    message(FATAL_ERROR "Battle Pay purchase-list request must be registered exactly once as recognition-only auth traffic")
endif()
string(FIND "${opcodes}" "DefC(0x18B2," raw_battle_pay_registration)
if(NOT raw_battle_pay_registration EQUAL -1)
    message(FATAL_ERROR "stale raw 0x18B2 registration duplicates the named Battle Pay route")
endif()
string(FIND "${opcode_header}" "CMSG_BATTLE_PAY_GET_PURCHASE_LIST            = 0x18B2" battle_pay_value)
if(battle_pay_value EQUAL -1)
    message(FATAL_ERROR "Battle Pay purchase-list request opcode drifted")
endif()

string(FIND "${opcode_header}" "SMSG_MISSILE_CANCEL" wrong_direction_missile_cancel)
if(NOT wrong_direction_missile_cancel EQUAL -1)
    message(FATAL_ERROR "0x1203 is a binary-proved inbound empty CMSG and must not remain exposed as SMSG_MISSILE_CANCEL")
endif()

set(selection_tokens
    "guid[7] = recv_data.ReadBit()"
    "guid[6] = recv_data.ReadBit()"
    "guid[5] = recv_data.ReadBit()"
    "guid[4] = recv_data.ReadBit()"
    "guid[3] = recv_data.ReadBit()"
    "guid[2] = recv_data.ReadBit()"
    "guid[1] = recv_data.ReadBit()"
    "guid[0] = recv_data.ReadBit()"
    "recv_data.ReadByteSeq(guid[0])"
    "recv_data.ReadByteSeq(guid[7])"
    "recv_data.ReadByteSeq(guid[3])"
    "recv_data.ReadByteSeq(guid[5])"
    "recv_data.ReadByteSeq(guid[1])"
    "recv_data.ReadByteSeq(guid[4])"
    "recv_data.ReadByteSeq(guid[6])"
    "recv_data.ReadByteSeq(guid[2])")
string(FIND "${misc}" "void WorldSession::HandleSetSelectionOpcode" selection_start)
string(FIND "${misc}" "void WorldSession::HandleStandStateChangeOpcode" selection_end)
if(selection_start EQUAL -1 OR selection_end LESS_EQUAL selection_start)
    message(FATAL_ERROR "set-selection handler body is missing")
endif()
math(EXPR selection_length "${selection_end} - ${selection_start}")
string(SUBSTRING "${misc}" ${selection_start} ${selection_length} selection_body)
set(previous_position -1)
foreach(token IN LISTS selection_tokens)
    string(FIND "${selection_body}" "${token}" position)
    if(position LESS_EQUAL previous_position)
        message(FATAL_ERROR "set-selection 18414 sequence missing or out of order: ${token}")
    endif()
    set(previous_position ${position})
endforeach()

set(sheathed_tokens
    "recv_data >> sheathed"
    "bool const hasSheathState = recv_data.ReadBit()"
    "if (!hasSheathState)"
    "if (sheathed >= MAX_SHEATH_STATE)"
    "GetPlayer()->SetSheath(SheathState(sheathed))")
string(FIND "${combat}" "void WorldSession::HandleSetSheathedOpcode" sheathed_start)
if(sheathed_start EQUAL -1)
    message(FATAL_ERROR "set-sheathed handler body is missing")
endif()
string(SUBSTRING "${combat}" ${sheathed_start} -1 sheathed_body)
set(previous_position -1)
foreach(token IN LISTS sheathed_tokens)
    string(FIND "${sheathed_body}" "${token}" position)
    if(position LESS_EQUAL previous_position)
        message(FATAL_ERROR "set-sheathed 18414 sequence missing or out of order: ${token}")
    endif()
    set(previous_position ${position})
endforeach()

string(FIND "${misc}" "void WorldSession::HandleStandStateChangeOpcode" stand_start)
string(FIND "${misc}" "void WorldSession::HandleBugOpcode" stand_end)
if(stand_start EQUAL -1 OR stand_end LESS_EQUAL stand_start)
    message(FATAL_ERROR "stand-state handler body is missing")
endif()
math(EXPR stand_length "${stand_end} - ${stand_start}")
string(SUBSTRING "${misc}" ${stand_start} ${stand_length} stand_body)
string(FIND "${stand_body}" "recv_data >> animstate;" stand_request)
string(FIND "${stand_body}" "_player->SetStandState(animstate);" stand_apply)
if(stand_request EQUAL -1 OR stand_apply LESS_EQUAL stand_request)
    message(FATAL_ERROR "stand-state request is not the 18414 uint32 body")
endif()
string(FIND "${unit}" "void Unit::SetStandState" stand_response_start)
string(FIND "${unit}" "bool Unit::IsPolymorphed" stand_response_end)
if(stand_response_start EQUAL -1 OR stand_response_end LESS_EQUAL stand_response_start)
    message(FATAL_ERROR "stand-state response sender body is missing")
endif()
math(EXPR stand_response_length "${stand_response_end} - ${stand_response_start}")
string(SUBSTRING "${unit}" ${stand_response_start} ${stand_response_length} stand_response_source)
string(FIND "${stand_response_source}" "WorldPacket data(SMSG_STANDSTATE_UPDATE, 1);" stand_response)
string(FIND "${stand_response_source}" "data << (uint8)state;" stand_response_body)
if(stand_response EQUAL -1 OR stand_response_body LESS_EQUAL stand_response)
    message(FATAL_ERROR "stand-state response is not the 18414 uint8 body")
endif()

string(FIND "${misc}" "MopHotfixPackets::ReadHotfixRequest(recv_data, request)" hotfix_parser)
if(hotfix_parser EQUAL -1)
    message(FATAL_ERROR "hotfix handler does not use the 18414 parser")
endif()

foreach(response IN ITEMS SMSG_UI_TIME SMSG_DB_REPLY)
    if(NOT opcodes MATCHES "DefS\\(${response},")
        message(FATAL_ERROR "${response} is not registered for server sends")
    endif()
    if(NOT session MATCHES "case ${response}:")
        message(FATAL_ERROR "${response} is not admitted through world-send suppression")
    endif()
endforeach()

string(FIND "${item}" "MopHotfixPackets::BuildDbReply(data, entry," db_reply_builder)
if(db_reply_builder EQUAL -1)
    message(FATAL_ERROR "item hotfix replies do not use the 18414 response builder")
endif()
if(misc MATCHES "ReadBits\\(23\\)")
    message(FATAL_ERROR "legacy 23-bit hotfix count remains")
endif()
string(FIND "${channel}" "MopChannelPackets::ReadJoinChannelRequest(recvPacket, request)" channel_parser)
if(channel_parser EQUAL -1)
    message(FATAL_ERROR "join-channel handler does not use the 18414 parser")
endif()
string(FIND "${character}" "MopClientRequestPackets::ReadLoadScreenRequest(recvPacket)" load_screen_parser)
if(load_screen_parser EQUAL -1)
    message(FATAL_ERROR "load-screen handler does not use the 18414 parser")
endif()

string(FIND "${misc}" "MopControlPackets::ReadMoveTimeSkipped(recv_data)" time_skipped_parser)
if(time_skipped_parser EQUAL -1)
    message(FATAL_ERROR "move-time-skipped handler does not use the 18414 parser")
endif()
string(FIND "${movement}" "MopControlPackets::ReadSetActiveMover(recv_data, request)" active_mover_parser)
if(active_mover_parser EQUAL -1)
    message(FATAL_ERROR "active-mover handler does not use the 18414 parser")
endif()

string(FIND "${voice}" "bool const voiceEnabled = recv_data.ReadBit();" voice_bit)
string(FIND "${voice}" "bool const microphoneEnabled = recv_data.ReadBit();" microphone_bit)
if(voice_bit EQUAL -1 OR microphone_bit EQUAL -1)
    message(FATAL_ERROR "voice-session handler does not consume the two 18414 bits")
endif()
if(voice MATCHES "read_skip<uint8>\\(\\)")
    message(FATAL_ERROR "legacy two-byte voice-session body remains")
endif()
