file(READ "${SOURCE_ROOT}/src/game/Object/Player.cpp" PLAYER_SOURCE)
file(READ "${SOURCE_ROOT}/src/game/WorldHandlers/Map.cpp" MAP_SOURCE)
file(READ "${SOURCE_ROOT}/src/game/WorldHandlers/CharacterHandler.cpp" CHARACTER_SOURCE)

string(FIND "${PLAYER_SOURCE}" "void Player::SendInitialPacketsBeforeAddToMap()" BEFORE_START)
string(FIND "${PLAYER_SOURCE}" "void Player::SendInitialPacketsAfterAddToMap()" AFTER_START)
string(FIND "${PLAYER_SOURCE}" "void Player::SetClientControl(" CONTROL_START)
string(FIND "${PLAYER_SOURCE}" "void Player::Uncharm()" UNCHARM_START)
if(BEFORE_START EQUAL -1 OR AFTER_START EQUAL -1 OR CONTROL_START EQUAL -1 OR UNCHARM_START EQUAL -1)
    message(FATAL_ERROR "Could not locate player initialization/control functions")
endif()

math(EXPR BEFORE_LENGTH "${AFTER_START} - ${BEFORE_START}")
math(EXPR AFTER_LENGTH "${CONTROL_START} - ${AFTER_START}")
math(EXPR CONTROL_LENGTH "${UNCHARM_START} - ${CONTROL_START}")
string(SUBSTRING "${PLAYER_SOURCE}" ${BEFORE_START} ${BEFORE_LENGTH} BEFORE_BODY)
string(SUBSTRING "${PLAYER_SOURCE}" ${AFTER_START} ${AFTER_LENGTH} AFTER_BODY)
string(SUBSTRING "${PLAYER_SOURCE}" ${CONTROL_START} ${CONTROL_LENGTH} CONTROL_BODY)

string(FIND "${BEFORE_BODY}" "SendActiveMover(" EARLY_ACTIVE_MOVER)
if(NOT EARLY_ACTIVE_MOVER EQUAL -1)
    message(FATAL_ERROR "Active mover must not be sent before Map::SendInitSelf")
endif()

string(REGEX MATCH "SetClientControl\\([ \\t]*this,[ \\t]*1[ \\t]*\\);" CONTROL_GRANT "${AFTER_BODY}")
string(REGEX MATCH "SendActiveMover\\([ \\t]*this[ \\t]*\\);" ACTIVE_MOVER "${AFTER_BODY}")
if(CONTROL_GRANT STREQUAL "" OR ACTIVE_MOVER STREQUAL "")
    message(FATAL_ERROR "After-map initialization must send control and active mover")
endif()

string(FIND "${AFTER_BODY}" "${CONTROL_GRANT}" CONTROL_GRANT_POS)
string(FIND "${AFTER_BODY}" "${ACTIVE_MOVER}" ACTIVE_MOVER_POS)
if(NOT CONTROL_GRANT_POS LESS ACTIVE_MOVER_POS)
    message(FATAL_ERROR "Control grant must precede active mover")
endif()

string(FIND "${PLAYER_SOURCE}" "MopControlPackets::BuildClientControlUpdate" CONTROL_BUILDER)
string(FIND "${PLAYER_SOURCE}" "MopControlPackets::BuildSetActiveMover" ACTIVE_BUILDER)
string(FIND "${CONTROL_BODY}" "data << target->GetPackGUID();" LEGACY_CONTROL)
if(CONTROL_BUILDER EQUAL -1 OR ACTIVE_BUILDER EQUAL -1)
    message(FATAL_ERROR "Player senders must use the reader-proven builders")
endif()
if(NOT LEGACY_CONTROL EQUAL -1)
    message(FATAL_ERROR "Legacy packed-GUID control body remains")
endif()

string(FIND "${MAP_SOURCE}" "SendInitSelf(player);" SELF_UPDATE)
if(SELF_UPDATE EQUAL -1)
    message(FATAL_ERROR "Map::Add no longer queues the self update")
endif()

string(FIND "${CHARACTER_SOURCE}" "pCurrChar->GetMap()->Add(pCurrChar)" MAP_ADD)
string(FIND "${CHARACTER_SOURCE}" "pCurrChar->SendInitialPacketsAfterAddToMap();" AFTER_CALL)
if(MAP_ADD EQUAL -1 OR AFTER_CALL EQUAL -1)
    message(FATAL_ERROR "Could not locate login Map::Add/after-map calls")
endif()
if(NOT MAP_ADD LESS AFTER_CALL)
    message(FATAL_ERROR "Login must call after-map initialization after Map::Add")
endif()
